/**
 * CLIExecutor — replaces SDKExecutor for interactive Claude CLI sessions.
 *
 * Spawns `claude` (WITHOUT `-p`) in interactive mode with `--output-format stream-json
 * --input-format stream-json --verbose`. This uses the Claude Max subscription for
 * billing (not the Agent SDK credit pool). The process stays alive for the entire
 * conversation lifetime. User messages are written to stdin as NDJSON lines; NDJSON
 * events are read from stdout and normalized via the same stream-normalizer pipeline.
 *
 * Key design points:
 * - Uses `child_process.spawn('claude', args)` directly — no SDK dependency
 * - Session ID captured from `system/init` event (same NDJSON shape)
 * - Resume via `--resume <sessionId>` CLI flag
 * - Slash commands (/compact, /clear) supported via stdin writes
 * - MCP servers configured via `--mcp-config <path>` (external stdio processes)
 *
 * Introduced for the Agent SDK → CLI migration (June 2026) to avoid
 * Agent SDK credit consumption under the new billing model.
 */

import { spawn, type ChildProcess } from 'node:child_process'
import { writeFileSync, mkdirSync, existsSync, unlinkSync } from 'node:fs'
import { app } from 'electron'
import { join } from 'node:path'
import { tmpdir } from 'node:os'
import type { StreamChunk } from './agent-base.service'
import { parseNdjsonStream, writeNdjsonMessage, buildUserMessage } from './cli-executor/ndjson-parser'
import {
  HeartbeatMonitor,
  TokenAccountant,
  TelemetryRecorder,
  ToolTracker,
  normalizeMessage,
  executorLog
} from './executor-utils/index'
import type { StreamState } from './executor-utils/index'

// ── Re-export types for external consumers ──
export type { TelemetryEntry } from './executor-utils/telemetry-recorder'
export type { TokenUsage } from './executor-utils/token-accountant'

/**
 * Terminal reason — why a CLI session stopped.
 * Matches the same values the SDK emits in result.terminal_reason.
 */
export type TerminalReason =
  | 'blocking_limit'
  | 'rapid_refill_breaker'
  | 'prompt_too_long'
  | 'image_error'
  | 'model_error'
  | 'aborted_streaming'
  | 'aborted_tools'
  | 'stop_hook_prevented'
  | 'hook_stopped'
  | 'tool_deferred'
  | 'max_turns'
  | 'completed'

// ── CLI Execute Options ──

export interface CLIExecuteOptions {
  /** User message or prompt to send — string for text, array for content blocks (images) */
  prompt: string | Array<Record<string, unknown>>
  /** System prompt (injected via --system-prompt flag on first launch) */
  systemPrompt: string
  /** Model identifier (e.g. 'claude-sonnet-4-6') */
  model: string
  /** Working directory for the CLI process */
  cwd: string
  /** Permission mode (mapped to --permission-mode flag) */
  permissionMode: 'default' | 'plan' | 'bypassPermissions' | 'acceptEdits' | 'auto' | 'dontAsk'
  /** Tools to allow (passed via --allowedTools) */
  allowedTools?: string[]
  /** Tools to disallow (passed via --disallowedTools) */
  disallowedTools?: string[]
  /** Session ID for resuming an existing conversation */
  resume?: string
  /** AbortController for cancelling the CLI process */
  abortController?: AbortController
  /** Heartbeat interval in ms (default: 15000) */
  heartbeatIntervalMs?: number
  /** Agent ID for logging attribution */
  agentId?: string
  /** Max agentic turns */
  maxTurns?: number
  /** Path to MCP config JSON file (generated by mcp-config-writer) */
  mcpConfigPath?: string
  /** Additional directories for monorepo support */
  additionalDirectories?: string[]
  /** Additional env vars to inject into the CLI subprocess */
  envOverrides?: Record<string, string>
  /** Enable auto-compact */
  autoCompactEnabled?: boolean
  /** Context window size for auto-compact threshold */
  contextWindowSize?: number
  /** Continue an existing session — used for multi-turn interactions within the same process */
  continueSession?: boolean
  /** Effort level — Claude Code 2.1+ supports all 5 levels natively: low, medium, high, xhigh, max */
  effort?: 'low' | 'medium' | 'high' | 'xhigh' | 'max'
  /** Completion goal — Claude works autonomously until this condition is met (Claude Code 2.1.139+) */
  goal?: string
  /** Enable 1M context beta */
  betas?: string[]
  /** Fallback model when primary unavailable */
  fallbackModel?: string
  /** Resume at a specific message point (undo support) */
  resumeSessionAt?: string
}

export interface CLIExecuteResult {
  sessionId?: string
  result?: string
  terminalReason?: TerminalReason
  sessionTitle?: string
  resultOrigin?: string
  tokenUsage: {
    input: number
    output: number
    cacheReadInputTokens: number
    cacheCreationInputTokens: number
  }
}

// ── CLIExecutor class ──

export class CLIExecutor {
  private cliProcess: ChildProcess | null = null
  private sessionId: string | undefined = undefined
  /** Temp file path for the current system prompt (cleaned up on process kill) */
  private systemPromptFile: string | null = null
  /** Persisted NDJSON iterator — survives across turns so multi-turn stdin/stdout works */
  private ndjsonIterator: AsyncGenerator<Record<string, unknown>> | null = null

  /** The active CLI process (for status checks) */
  getProcess(): ChildProcess | null {
    return this.cliProcess
  }

  /** Get the captured session ID */
  getSessionId(): string | undefined {
    return this.sessionId
  }

  /**
   * Check if the CLI process is still alive.
   * Used by AgentSessionService to determine if a send() can reuse the process.
   */
  isAlive(): boolean {
    return this.cliProcess !== null && !this.cliProcess.killed && this.cliProcess.exitCode === null
  }

  /**
   * Execute a query via the interactive Claude CLI.
   *
   * If `continueSession` is true and a process is already alive, writes
   * the prompt to stdin (multi-turn mode). Otherwise spawns a new process.
   *
   * Returns an async generator of StreamChunks — same interface as SDKExecutor.
   */
  async *execute(
    options: CLIExecuteOptions
  ): AsyncGenerator<StreamChunk & { _meta?: CLIExecuteResult }> {
    const telemetry = new TelemetryRecorder(options.model)
    const heartbeat = new HeartbeatMonitor(options.heartbeatIntervalMs ?? 15000)
    const tokens = new TokenAccountant()
    const tools = new ToolTracker()
    const state: StreamState = { streamedTextLength: 0 }

    heartbeat.start()

    try {
      // If continuing an existing session, write the prompt to stdin
      if (options.continueSession && this.isAlive() && this.cliProcess?.stdin) {
        executorLog.info('[CLI:send] Continuing existing session — writing message to stdin')
        writeNdjsonMessage(this.cliProcess.stdin, buildUserMessage(options.prompt))
      } else {
        // Spawn a fresh CLI process
        const args = this.buildCLIArgs(options)
        const env = this.buildProcessEnv(options)

        executorLog.info(
          `[CLI:spawn] claude ${args.join(' ').replace(/--system-prompt ".*?"/, '--system-prompt "..."')}`
        )
        executorLog.info(`[CLI:args] ${args.join(' ')}`)

        // Kill any existing process before spawning new one
        await this.killProcess()

        this.cliProcess = spawn('claude', args, {
          cwd: options.cwd,
          env,
          stdio: ['pipe', 'pipe', 'pipe'],
          // Don't kill the process when the parent exits — we manage lifecycle explicitly
          detached: false
        })

        // Wire abort controller to process kill
        if (options.abortController) {
          const signal = options.abortController.signal
          if (signal.aborted) {
            this.cliProcess.kill('SIGTERM')
          } else {
            signal.addEventListener(
              'abort',
              () => {
                this.killProcess()
              },
              { once: true }
            )
          }
        }

        // Log stderr for diagnostics (not fatal — CLI writes progress info there)
        this.cliProcess.stderr?.on('data', (data: Buffer) => {
          const text = data.toString('utf-8').trim()
          if (text) {
            executorLog.info(`[CLI:stderr] ${text.slice(0, 500)}`)
          }
        })

        // Handle process exit
        this.cliProcess.on('exit', (code, signal) => {
          executorLog.info(`[CLI:exit] code=${code} signal=${signal}`)
          this.cliProcess = null
        })

        this.cliProcess.on('error', (err) => {
          executorLog.error('[CLI:error]', err)
          this.cliProcess = null
        })

        // Write the initial user message to stdin
        if (this.cliProcess.stdin) {
          writeNdjsonMessage(this.cliProcess.stdin, buildUserMessage(options.prompt))
        }
      }

      // Read NDJSON from stdout — reuse the iterator across turns so the
      // underlying stream stays open for multi-turn interactive mode.
      if (!this.ndjsonIterator) {
        if (!this.cliProcess?.stdout) {
          yield { type: 'error', error: 'CLI process stdout not available' }
          return
        }
        this.ndjsonIterator = parseNdjsonStream(this.cliProcess.stdout, executorLog)
      }

      // Manual .next() loop instead of `for await...of` — breaking out of
      // `for await` calls iterator.return() which permanently closes the
      // generator, making it unusable for subsequent turns. By calling .next()
      // directly we can stop consuming on a `result` event without destroying
      // the iterator, so multi-turn stdin/stdout works.
      let msgCount = 0
      try {
        while (true) {
          const iterResult = await this.ndjsonIterator.next()
          if (iterResult.done) {
            executorLog.info('[CLI:stream] Iterator exhausted (process ended)')
            this.ndjsonIterator = null
            break
          }

          const msg = iterResult.value
          heartbeat.touch()
          msgCount++

          // Log first 5 messages for diagnostics — helps verify CLI is producing expected types
          if (msgCount <= 5) {
            executorLog.info(`[CLI:msg#${msgCount}] type=${msg.type} subtype=${(msg as Record<string, unknown>).subtype ?? 'none'}`)
          }

          // Emit pending heartbeat if timer fired between iterations
          if (heartbeat.consumeHeartbeat()) {
            yield { type: 'status', content: 'heartbeat' }
          }

          // Capture session ID from system/init (identical field to SDK)
          if (msg.type === 'system' && msg.subtype === 'init') {
            this.sessionId = msg.session_id as string | undefined
            state.sessionId = this.sessionId
          }

          // Delegate to existing stream normalizer — same NDJSON format
          yield* normalizeMessage(msg, tools, tokens, state, options.cwd)

          // In interactive mode (no -p), the CLI stays alive after responding.
          // Stop consuming on the result event (end-of-turn) so the caller can
          // finalize. The iterator stays alive for the next turn.
          if (msg.type === 'result') {
            executorLog.info('[CLI:result-received] Turn complete — pausing stream read')
            break
          }
        }
      } catch (error) {
        // Stream interrupted (abort, process kill, etc.)
        if ((error as NodeJS.ErrnoException).code !== 'ERR_STREAM_PREMATURE_CLOSE') {
          throw error
        }
        executorLog.info('[CLI:stream] Stream closed (process ended or aborted)')
        this.ndjsonIterator = null
      }
      executorLog.info(`[CLI:stream-end] Total NDJSON messages received: ${msgCount}`)
    } catch (error) {
      executorLog.error('CLI execution error:', error)
      telemetry.recordFailure(error as Error)
      yield {
        type: 'error',
        error: `CLI execution failed: ${(error as Error).message}`
      }
    } finally {
      heartbeat.stop()
    }

    // Telemetry: record success
    const tokenSummary = tokens.getSummary()
    telemetry.finalize(tokenSummary)

    // Yield final metadata chunk (callers check for _meta)
    yield {
      type: 'status',
      content: 'complete',
      _meta: {
        sessionId: state.sessionId,
        result: state.resultText,
        terminalReason: state.terminalReason,
        sessionTitle: state.sessionTitle,
        resultOrigin: state.resultOrigin,
        tokenUsage: tokenSummary
      }
    } as StreamChunk & { _meta: CLIExecuteResult }
  }

  /**
   * Execute a single prompt and collect the full text result (non-streaming).
   * Used for decomposition and other one-shot queries.
   */
  async executeAndCollect(options: CLIExecuteOptions): Promise<{
    result: string
    sessionId?: string
    tokenUsage: { input: number; output: number }
  }> {
    let result = ''
    let sessionId: string | undefined
    const totalUsage = { input: 0, output: 0 }

    for await (const chunk of this.execute(options)) {
      if (chunk.type === 'text' && chunk.content) {
        result += chunk.content
      }
      if ('_meta' in chunk && chunk._meta) {
        const meta = chunk._meta as CLIExecuteResult
        sessionId = meta.sessionId
        totalUsage.input = meta.tokenUsage.input
        totalUsage.output = meta.tokenUsage.output
        if (!result && meta.result) {
          result = typeof meta.result === 'string' ? meta.result : JSON.stringify(meta.result)
        }
      }
    }

    return { result, sessionId, tokenUsage: totalUsage }
  }

  /**
   * Send a slash command to the interactive CLI (e.g. /compact, /clear).
   * Only works when a process is alive.
   */
  sendSlashCommand(command: string): void {
    if (!this.isAlive() || !this.cliProcess?.stdin) {
      executorLog.warn(`[CLI:slash] Cannot send "${command}" — no active process`)
      return
    }
    executorLog.info(`[CLI:slash] Sending: ${command}`)
    this.cliProcess.stdin.write(command + '\n')
  }

  /**
   * Send /compact to trigger context compaction via the interactive CLI.
   */
  compact(): void {
    this.sendSlashCommand('/compact')
  }

  /**
   * Change the CLI's permission mode mid-session via the control protocol.
   * Sends a set_permission_mode control_request to stdin.
   * Requires `--allow-dangerously-skip-permissions` to be present in the CLI args
   * for runtime elevation to 'bypassPermissions'.
   */
  setPermissionMode(
    mode: 'plan' | 'auto' | 'bypassPermissions' | 'default' | 'acceptEdits' | 'dontAsk'
  ): void {
    if (!this.isAlive() || !this.cliProcess?.stdin) {
      executorLog.warn('[CLI:setPermissionMode] Cannot set mode — no active process')
      return
    }
    const controlRequest = {
      type: 'control_request',
      request_id: `perm_${Date.now()}_${Math.random().toString(36).slice(2, 6)}`,
      request: {
        subtype: 'set_permission_mode',
        mode
      }
    }
    executorLog.info(`[CLI:setPermissionMode] Sending: ${mode}`)
    writeNdjsonMessage(this.cliProcess.stdin, controlRequest)
  }

  /**
   * Kill the active CLI process. SIGTERM → 5s → SIGKILL.
   * Matches the existing process termination pattern in the codebase.
   */
  async killProcess(): Promise<void> {
    if (!this.cliProcess) return

    const proc = this.cliProcess
    this.cliProcess = null
    this.ndjsonIterator = null

    return new Promise<void>((resolve) => {
      const forceKillTimer = setTimeout(() => {
        try {
          proc.kill('SIGKILL')
        } catch {
          // Already dead
        }
        this.cleanupSystemPromptFile()
        resolve()
      }, 5000)

      proc.once('exit', () => {
        clearTimeout(forceKillTimer)
        this.cleanupSystemPromptFile()
        resolve()
      })

      try {
        proc.kill('SIGTERM')
      } catch {
        clearTimeout(forceKillTimer)
        this.cleanupSystemPromptFile()
        resolve()
      }
    })
  }

  // ── Private helpers ──

  /**
   * Build CLI arguments from execute options.
   * Maps SDK-style options to their `claude` CLI flag equivalents.
   */
  private buildCLIArgs(options: CLIExecuteOptions): string[] {
    const args: string[] = [
      // Core interactive mode flags — stream-json enables NDJSON on stdout/stdin
      '--output-format',
      'stream-json',
      '--input-format',
      'stream-json',
      '--verbose',
      // Include partial messages for real-time streaming (same as SDK's includePartialMessages)
      '--include-partial-messages',
      // Allow runtime switch to bypassPermissions via set_permission_mode control request.
      // Without this flag, the CLI rejects mid-session elevation to bypassPermissions.
      '--allow-dangerously-skip-permissions'
    ]

    // Model
    if (options.model) {
      args.push('--model', options.model)
    }

    // Permission mode
    if (options.permissionMode) {
      // Map SDK permission modes to CLI equivalents.
      // The CLI's --permission-mode flag accepts the literal mode name.
      // Note: 'bypassPermissions' is the correct value (not 'dangerously-skip-permissions',
      // which is a standalone flag, not a --permission-mode value).
      const modeMap: Record<string, string> = {
        default: 'default',
        plan: 'plan',
        bypassPermissions: 'bypassPermissions',
        acceptEdits: 'acceptEdits',
        auto: 'auto',
        dontAsk: 'dontAsk'
      }
      const cliMode = modeMap[options.permissionMode] ?? 'default'
      args.push('--permission-mode', cliMode)
    }

    // System prompt — written to a temp file to avoid shell escaping issues
    // and OS arg-length limits (system prompts can be 15K-25K chars).
    if (options.systemPrompt) {
      const promptFilePath = this.writeSystemPromptFile(options.systemPrompt)
      args.push('--system-prompt-file', promptFilePath)
    }

    // Session resume
    if (options.resume) {
      args.push('--resume', options.resume)
    }

    // Resume at specific message (undo support)
    if (options.resumeSessionAt) {
      args.push('--resume-session-at', options.resumeSessionAt)
    }

    // Max turns
    if (options.maxTurns) {
      args.push('--max-turns', String(options.maxTurns))
    }

    // MCP config path (external servers)
    if (options.mcpConfigPath) {
      args.push('--mcp-config', options.mcpConfigPath)
    }

    // Allowed tools
    if (options.allowedTools?.length) {
      args.push('--allowedTools', options.allowedTools.join(','))
    }

    // Disallowed tools
    if (options.disallowedTools?.length) {
      args.push('--disallowedTools', options.disallowedTools.join(','))
    }

    // Additional directories
    if (options.additionalDirectories?.length) {
      for (const dir of options.additionalDirectories) {
        args.push('--add-dir', dir)
      }
    }

    // Effort level — Claude Code 2.1+ supports all 5 levels natively
    if (options.effort) {
      args.push('--effort', options.effort)
    }

    // Betas (1M context)
    if (options.betas?.length) {
      for (const beta of options.betas) {
        args.push('--beta', beta)
      }
    }

    // Fallback model
    if (options.fallbackModel) {
      args.push('--fallback-model', options.fallbackModel)
    }

    // Goal — autonomous completion condition (Claude Code 2.1.139+)
    if (options.goal) {
      args.push('--goal', options.goal)
    }

    return args
  }

  /**
   * Write a system prompt to a temp file.
   * Returns the absolute path to the file. The file is cleaned up when
   * the CLI process exits (via killProcess) or on the next call.
   */
  private writeSystemPromptFile(prompt: string): string {
    // Clean up previous file if any
    this.cleanupSystemPromptFile()

    const dir = join(tmpdir(), 'code-atelier-prompts')
    if (!existsSync(dir)) {
      mkdirSync(dir, { recursive: true })
    }
    const filePath = join(dir, `system-prompt-${Date.now()}.md`)
    writeFileSync(filePath, prompt, 'utf-8')
    this.systemPromptFile = filePath
    return filePath
  }

  /**
   * Remove the current system prompt temp file.
   */
  private cleanupSystemPromptFile(): void {
    if (this.systemPromptFile) {
      try {
        unlinkSync(this.systemPromptFile)
      } catch {
        // Non-fatal — file may already be gone
      }
      this.systemPromptFile = null
    }
  }

  /**
   * Build the process environment.
   * Includes current env + any user-provided overrides + app identification.
   */
  private buildProcessEnv(options: CLIExecuteOptions): Record<string, string | undefined> {
    return {
      ...process.env,
      ...(options.envOverrides ?? {}),
      CLAUDE_AGENT_SDK_CLIENT_APP: `code-atelier/${app.getVersion()}`
    }
  }
}

/**
 * Resolve the Claude CLI binary path for packaged Electron apps.
 * In dev mode, returns undefined (CLI found via PATH).
 * In packaged apps, checks standard install locations.
 */
export function resolveClaudeBinaryPath(): string | undefined {
  if (!app.isPackaged) return undefined

  // Standard macOS installation paths
  const candidates = [
    '/usr/local/bin/claude',
    join(process.env.HOME ?? '', '.claude', 'bin', 'claude'),
    '/opt/homebrew/bin/claude'
  ]

  // In packaged apps, prefer the system-installed claude binary
  for (const candidate of candidates) {
    try {
      const fs = require('node:fs')
      if (fs.existsSync(candidate)) {
        return candidate
      }
    } catch {
      // Continue checking
    }
  }

  return undefined
}

