/**
 * CLIExecutor — replaces SDKExecutor for interactive Claude CLI sessions.
 *
 * Spawns `claude` (WITHOUT `-p`) in interactive mode with `--output-format stream-json
 * --input-format stream-json --verbose`. This uses the Claude Max subscription for
 * billing (not the Agent SDK credit pool). The process stays alive for the entire
 * conversation lifetime. User messages are written to stdin as NDJSON lines; NDJSON
 * events are read from stdout and normalized via the same stream-normalizer pipeline.
 *
 * Key design points:
 * - Uses `child_process.spawn('claude', args)` directly — no SDK dependency
 * - Session ID captured from `system/init` event (same NDJSON shape)
 * - Resume via `--resume <sessionId>` CLI flag
 * - Slash commands (/compact, /clear) supported via stdin writes
 * - MCP servers configured via `--mcp-config <path>` (external stdio processes)
 *
 * Introduced for the Agent SDK → CLI migration (June 2026) to avoid
 * Agent SDK credit consumption under the new billing model.
 */

import { spawn, type ChildProcess } from 'node:child_process'
import { writeFileSync, mkdirSync, existsSync, unlinkSync, readdirSync, statSync } from 'node:fs'
import { createHash, randomUUID } from 'node:crypto'
import { app } from 'electron'
import { join } from 'node:path'
import { tmpdir } from 'node:os'
import type { StreamChunk } from './agent-base.service'
import {
  parseNdjsonStream,
  writeNdjsonMessage,
  buildUserMessage
} from './cli-executor/ndjson-parser'
import {
  HeartbeatMonitor,
  TokenAccountant,
  TelemetryRecorder,
  ToolTracker,
  normalizeMessage,
  executorLog
} from './executor-utils/index'
import { buildEnvWithPath } from './env-utils'
import type { StreamState } from './executor-utils/index'

// ── Re-export types for external consumers ──
export type { TelemetryEntry } from './executor-utils/telemetry-recorder'
export type { TokenUsage } from './executor-utils/token-accountant'

/**
 * Terminal reason — why a CLI session stopped.
 * Matches the same values the SDK emits in result.terminal_reason.
 */
export type TerminalReason =
  | 'blocking_limit'
  | 'rapid_refill_breaker'
  | 'prompt_too_long'
  | 'image_error'
  | 'model_error'
  | 'aborted_streaming'
  | 'aborted_tools'
  | 'stop_hook_prevented'
  | 'hook_stopped'
  | 'tool_deferred'
  | 'max_turns'
  | 'completed'

// ── CLI Execute Options ──

export interface CLIExecuteOptions {
  /** User message or prompt to send — string for text, array for content blocks (images) */
  prompt: string | Array<Record<string, unknown>>
  /** System prompt (injected via --system-prompt flag on first launch) */
  systemPrompt: string
  /** Model identifier (e.g. 'claude-sonnet-4-6') */
  model: string
  /** Working directory for the CLI process */
  cwd: string
  /** Permission mode (mapped to --permission-mode flag) */
  permissionMode: 'default' | 'plan' | 'bypassPermissions' | 'acceptEdits' | 'auto' | 'dontAsk'
  /** Tools to allow (passed via --allowedTools) */
  allowedTools?: string[]
  /** Tools to disallow (passed via --disallowedTools) */
  disallowedTools?: string[]
  /** MCP tool name to use for permission prompts (--permission-prompt-tool flag).
   *  When set, the CLI invokes this tool instead of auto-denying permission-gated operations. */
  permissionPromptTool?: string
  /** Session ID for resuming an existing conversation */
  resume?: string
  /** AbortController for cancelling the CLI process */
  abortController?: AbortController
  /** Heartbeat interval in ms (default: 5000) */
  heartbeatIntervalMs?: number
  /** Agent ID for logging attribution */
  agentId?: string
  /** Max agentic turns */
  maxTurns?: number
  /** Path to MCP config JSON file (generated by mcp-config-writer) */
  mcpConfigPath?: string
  /** Additional directories for monorepo support */
  additionalDirectories?: string[]
  /** Additional env vars to inject into the CLI subprocess */
  envOverrides?: Record<string, string>
  /** Enable auto-compact */
  autoCompactEnabled?: boolean
  /** Context window size for auto-compact threshold */
  contextWindowSize?: number
  /** Continue an existing session — used for multi-turn interactions within the same process */
  continueSession?: boolean
  /** Effort level — Claude Code 2.1+ supports all 5 levels natively: low, medium, high, xhigh, max */
  effort?: 'low' | 'medium' | 'high' | 'xhigh' | 'max'
  /** Completion goal — Claude works autonomously until this condition is met.
   *  Dual delivery: (1) appended to system prompt as ## Completion Goal for persistent
   *  visibility, and (2) queued as a `/goal` slash command via stdin for native enforcement
   *  (Haiku-based stop-hook evaluator). */
  goal?: string
  /**
   * Goal delivery mode:
   * - `'advisory'` (default): goal only in system prompt (## Completion Goal section).
   * - `'enforce'`: additionally queues `/goal <condition>` via stdin for native
   *   stop-hook enforcement (Haiku evaluator). Use for phases where structured
   *   output MUST be produced (plan, tasks, review, build, verify).
   */
  goalMode?: 'advisory' | 'enforce'
  /** Enable 1M context beta */
  betas?: string[]
  /** Fallback model when primary unavailable */
  fallbackModel?: string
  /** Resume at a specific message point (undo support) */
  resumeSessionAt?: string
  /** Max thinking tokens per turn — advisory only.
   *  Dropped silently (no CLI equivalent; effort level caps reasoning). */
  thinkingBudget?: number
}

export interface CLIExecuteResult {
  sessionId?: string
  result?: string
  terminalReason?: TerminalReason
  sessionTitle?: string
  resultOrigin?: string
  tokenUsage: {
    input: number
    output: number
    cacheReadInputTokens: number
    cacheCreationInputTokens: number
    /** Current context occupancy (latest round-trip prompt size, not the sum). */
    contextWindowTokens?: number
  }
}

// ── CLIExecutor class ──

/**
 * Per-message timeout for iterator.next() — prevents indefinite hangs when
 * the CLI stalls with no tool call pending. Disabled during pending tool
 * calls (e.g., ask_user waiting for human interaction).
 */
const MESSAGE_TIMEOUT_MS = 5 * 60_000 // 5 minutes

/**
 * Generous timeout for MCP tool execution results. Applied when tools are
 * pending BUT none of them are ask_user-type (which legitimately wait for
 * human input). Prevents zombie CLI processes when MCP tools deadlock.
 * The 5-min main-process safety timer provides a second layer, but this
 * timeout addresses the root cause at the executor level.
 */
const TOOL_RESULT_TIMEOUT_MS = 10 * 60_000 // 10 minutes

/**
 * How often to log a breadcrumb while a read is parked. Applies to every wait,
 * including the deliberately untimed human-input wait — the point is that a
 * stalled executor always leaves a trail in main.log.
 */
const WAIT_BREADCRUMB_MS = 60_000 // 1 minute

/** Maximum character length for a /goal condition sent to the CLI. */
const GOAL_MAX_CHARS = 4_000

/** Words that, when a goal condition starts with them, collide with /goal subcommands. */
const GOAL_CLEAR_ALIASES = /^(clear|stop|off|reset|none|cancel)\b/i

/** Regex for stderr patterns that indicate real errors (not progress info). */
const STDERR_ERROR_PATTERN = /error|fatal|panic|ENOENT|EACCES|permission denied|segfault|SIGABRT/i

export class CLIExecutor {
  private cliProcess: ChildProcess | null = null
  private sessionId: string | undefined = undefined
  /** Temp file path for the current system prompt (cleaned up on process kill) */
  private systemPromptFile: string | null = null
  /** Hash of last written system prompt — avoids rewriting identical content to disk. */
  private lastSystemPromptHash: string | null = null
  /** Persisted NDJSON iterator — survives across turns so multi-turn stdin/stdout works */
  private ndjsonIterator: AsyncGenerator<Record<string, unknown>> | null = null
  /**
   * Ready-state flag for multi-turn stdin writes.
   * Set to true after receiving a `result` event (end-of-turn),
   * set to false immediately after writing a new message.
   * Prevents writing while the CLI is still processing a previous turn.
   */
  private cliReadyForInput = false
  /** Last captured stderr error lines — used to provide context when CLI exits with non-zero code */
  private lastStderrError: string | null = null
  /** Exit code from the most recent process exit — checked after stream exhausts */
  private lastExitCode: number | null = null
  /** Whether a /goal command was queued for the current turn — enables trailing-result drain */
  private goalQueuedForTurn = false

  /**
   * Rejects as soon as the current child process exits or errors.
   *
   * Every await on the NDJSON iterator races this. Without it, a turn parked
   * on `iterator.next()` can outlive the process that was supposed to feed it:
   * the `exit` handler nulls `cliProcess` but does not end stdout, so the
   * `for await` inside parseNdjsonStream never completes. That is survivable
   * on the timeout-guarded branches, but the ask_user branch has NO timeout by
   * design (a human may take arbitrarily long), so a dead child there parks
   * the read loop forever — silent, with the stream lock still held.
   *
   * Null while no process is running. Always has a no-op catch attached so a
   * rejection nobody happens to be racing can't become an unhandled rejection.
   */
  private exitSignal: Promise<never> | null = null
  /** Rejector for `exitSignal`, invoked from the process 'exit'/'error' handlers. */
  private rejectExitSignal: ((err: Error) => void) | null = null

  /** Get the captured session ID */
  getSessionId(): string | undefined {
    return this.sessionId
  }

  /**
   * Arm a fresh exit signal for a newly spawned process. Any previous signal is
   * settled first so a stale one can never reject a future turn.
   */
  private armExitSignal(): void {
    this.disarmExitSignal('superseded by new process')
    this.exitSignal = new Promise<never>((_, reject) => {
      this.rejectExitSignal = reject
    })
    // The signal is only consumed when a read is actually in flight. Attaching
    // a sink here keeps an unraced rejection from surfacing as an unhandled one.
    this.exitSignal.catch(() => {})
  }

  /** Settle and clear the current exit signal. */
  private disarmExitSignal(reason: string): void {
    this.rejectExitSignal?.(new Error(reason))
    this.rejectExitSignal = null
    this.exitSignal = null
  }

  /**
   * Race a read against process death.
   *
   * `timeoutMs === null` means "no wall-clock limit" (human input) — but the
   * exit signal still applies, because no human can answer a prompt whose
   * process is gone.
   */
  private async raceRead(
    read: Promise<IteratorResult<Record<string, unknown>>>,
    timeoutMs: number | null,
    timeoutMessage: string
  ): Promise<IteratorResult<Record<string, unknown>>> {
    const contenders: Array<Promise<IteratorResult<Record<string, unknown>>>> = [read]
    if (this.exitSignal) contenders.push(this.exitSignal)

    let timeoutHandle: ReturnType<typeof setTimeout> | undefined
    if (timeoutMs !== null) {
      contenders.push(
        new Promise<never>((_, reject) => {
          timeoutHandle = setTimeout(() => reject(new Error(timeoutMessage)), timeoutMs)
        })
      )
    }

    try {
      return await Promise.race(contenders)
    } finally {
      clearTimeout(timeoutHandle)
    }
  }

  /**
   * Emit a periodic breadcrumb while a read is parked.
   *
   * The 35-minute production hang was diagnosable only as "main.log stops":
   * a parked await produces no output at all, so an indefinite wait and a dead
   * main process look identical after the fact. This makes waiting observable
   * — every WAIT_BREADCRUMB_MS the log records what is being waited on and for
   * how long, so the next occurrence is evidence rather than silence.
   */
  private async withWaitBreadcrumb<T>(
    label: string,
    tools: ToolTracker,
    run: () => Promise<T>
  ): Promise<T> {
    const startedAt = Date.now()
    const timer = setInterval(() => {
      const waitedSec = Math.round((Date.now() - startedAt) / 1000)
      executorLog.warn(
        `[CLI:await-breadcrumb] still waiting on ${label} after ${waitedSec}s ` +
          `(pending=${tools.pendingToolCount} names=[${tools.pendingToolNames.join(', ')}] ` +
          `alive=${this.isAlive()} pid=${this.cliProcess?.pid ?? 'none'})`
      )
    }, WAIT_BREADCRUMB_MS)
    // Never hold the event loop open purely for diagnostics.
    timer.unref?.()

    try {
      return await run()
    } finally {
      clearInterval(timer)
    }
  }

  /**
   * Check if the CLI process is still alive.
   * Used by AgentSessionService to determine if a send() can reuse the process.
   */
  isAlive(): boolean {
    return this.cliProcess !== null && !this.cliProcess.killed && this.cliProcess.exitCode === null
  }

  /**
   * Execute a query via the interactive Claude CLI.
   *
   * If `continueSession` is true and a process is already alive, writes
   * the prompt to stdin (multi-turn mode). Otherwise spawns a new process.
   *
   * Returns an async generator of StreamChunks — same interface as SDKExecutor.
   */
  async *execute(
    options: CLIExecuteOptions
  ): AsyncGenerator<StreamChunk & { _meta?: CLIExecuteResult }> {
    const telemetry = new TelemetryRecorder(options.model)
    const heartbeat = new HeartbeatMonitor(options.heartbeatIntervalMs ?? 5000)
    const tokens = new TokenAccountant()
    const tools = new ToolTracker()
    const state: StreamState = { streamedTextLength: 0 }

    // Reset per-execution error state
    this.lastStderrError = null
    this.lastExitCode = null

    heartbeat.start()

    try {
      // If continuing an existing session, write the prompt to stdin
      if (options.continueSession && this.isAlive() && this.cliProcess?.stdin) {
        if (!this.cliReadyForInput) {
          executorLog.warn(
            '[CLI:send] CLI not ready for input — previous turn may still be processing'
          )
        }
        executorLog.info('[CLI:send] Continuing existing session — writing message to stdin')
        await this.writeToStdin(buildUserMessage(options.prompt))

        // Queue /goal as a second stdin message (continue-session path) — enforce mode only
        const effectiveGoalMode = options.goalMode ?? 'advisory'
        const goalCmd =
          options.goal && effectiveGoalMode === 'enforce' ? buildGoalCommand(options.goal) : null
        if (goalCmd && this.cliProcess?.stdin) {
          await this.writeToStdin(buildUserMessage(goalCmd))
          this.goalQueuedForTurn = true
          executorLog.info(`[CLI:goal] queued condition (${goalCmd.length} chars)`)
        } else {
          this.goalQueuedForTurn = false
        }
      } else {
        await this.spawnCLIProcess(options)
      }

      // Read NDJSON from stdout — reuse the iterator across turns so the
      // underlying stream stays open for multi-turn interactive mode.
      if (!this.ndjsonIterator) {
        if (!this.cliProcess?.stdout) {
          yield { type: 'error', error: 'CLI process stdout not available' }
          return
        }
        this.ndjsonIterator = parseNdjsonStream(this.cliProcess.stdout, executorLog)
      }

      // Manual .next() loop instead of `for await...of` — breaking out of
      // `for await` calls iterator.return() which permanently closes the
      // generator, making it unusable for subsequent turns. By calling .next()
      // directly we can stop consuming on a `result` event without destroying
      // the iterator, so multi-turn stdin/stdout works.
      let msgCount = 0
      let lastLoggedPendingTools = 0 // throttle: only log on transitions (0→N or N→0)
      const goalWasQueued = this.goalQueuedForTurn
      try {
        while (true) {
          // Per-message timeout prevents indefinite hangs when CLI stalls
          // (e.g., MCP tool deadlock). When tool calls are pending:
          //   • ask_user/elicitation tools: timeout fully disabled (human input)
          //   • other MCP tools: TOOL_RESULT_TIMEOUT_MS (10 min) prevents zombie processes
          // The process exit (stream close) is a fallback termination signal.
          let iterResult: IteratorResult<Record<string, unknown>>
          if (tools.pendingToolCount > 0) {
            // Tool call in flight — use generous timeout unless waiting for
            // human input (ask_user / elicitation), which has no timeout.
            if (tools.hasAskUserPending()) {
              // Human input has no wall-clock timeout — the user decides when to
              // respond. The exit signal still applies (see raceRead): a prompt
              // whose process has died can never be answered, and parking here
              // forever is what wedges the conversation lock.
              if (lastLoggedPendingTools === 0) {
                executorLog.info(
                  `[CLI:await] Waiting for human input (${tools.pendingToolCount} pending: ${tools.pendingToolNames.join(', ')}) — wall-clock timeout suspended, exit signal armed`
                )
              }
              lastLoggedPendingTools = tools.pendingToolCount
              iterResult = await this.withWaitBreadcrumb('human-input', tools, () =>
                this.raceRead(this.ndjsonIterator!.next(), null, '')
              )
            } else {
              // MCP tool execution: generous timeout prevents indefinite hangs
              // Log only on 0→N transition (not per message)
              if (lastLoggedPendingTools === 0) {
                executorLog.info(
                  `[CLI:await] Waiting for tool result (${tools.pendingToolCount} pending: ${tools.pendingToolNames.join(', ')}) — ${TOOL_RESULT_TIMEOUT_MS / 1000}s timeout`
                )
              }
              lastLoggedPendingTools = tools.pendingToolCount
              iterResult = await this.withWaitBreadcrumb('tool-result', tools, () =>
                this.raceRead(
                  this.ndjsonIterator!.next(),
                  TOOL_RESULT_TIMEOUT_MS,
                  `CLI tool result timeout — no response from MCP tool for ${TOOL_RESULT_TIMEOUT_MS / 60_000} minutes`
                )
              )
            }
          } else {
            // Log tool-complete transition (N→0) once
            if (lastLoggedPendingTools > 0) {
              executorLog.debug(
                `[CLI:await] Tool calls resolved (was ${lastLoggedPendingTools} pending)`
              )
              lastLoggedPendingTools = 0
            }
            // No tools pending — use normal timeout to detect CLI stalls
            iterResult = await this.raceRead(
              this.ndjsonIterator.next(),
              MESSAGE_TIMEOUT_MS,
              `CLI message timeout — no NDJSON received for ${MESSAGE_TIMEOUT_MS / 1000}s`
            )
          }
          if (iterResult.done) {
            executorLog.info('[CLI:stream] Iterator exhausted (process ended)')
            this.ndjsonIterator = null
            break
          }

          const msg = iterResult.value
          heartbeat.touch()
          msgCount++

          // Log first 5 messages for diagnostics — helps verify CLI is producing expected types
          if (msgCount <= 5) {
            executorLog.info(
              `[CLI:msg#${msgCount}] type=${msg.type} subtype=${(msg as Record<string, unknown>).subtype ?? 'none'}`
            )
          }

          // Emit pending heartbeat if timer fired between iterations
          if (heartbeat.consumeHeartbeat()) {
            yield { type: 'status', content: 'heartbeat' }
          }

          // Capture session ID from system/init (identical field to SDK)
          if (msg.type === 'system' && msg.subtype === 'init') {
            this.sessionId = msg.session_id as string | undefined
            state.sessionId = this.sessionId
          }

          // Delegate to existing stream normalizer — same NDJSON format
          yield* normalizeMessage(msg, tools, tokens, state, options.cwd)

          // In interactive mode (no -p), the CLI stays alive after responding.
          // Finalize on the FIRST result event — always. When a /goal was queued,
          // the CLI may emit a trailing second result for the /goal command.
          // We drain it defensively (1.5s race) so it can't poison the next turn.
          if (msg.type === 'result') {
            this.cliReadyForInput = true
            this.goalQueuedForTurn = false
            // A turn that produced its result owes no further tool results.
            // Anything still pending was never consumed (e.g. a tool_result
            // that arrived without a tool_use_id) — carrying it forward pins
            // pendingToolCount above zero and wedges the next turn on the
            // tool-result timeout branch with a stale map.
            if (tools.pendingToolCount > 0) {
              executorLog.warn(
                `[CLI:pending-leak] n=${tools.pendingToolCount} names=[${tools.pendingToolNames.join(', ')}] — clearing at end of turn`
              )
              tools.clear()
            }
            // Stop heartbeat immediately — the stream is pausing between turns
            // and no more activity is expected until the next send().  Without
            // this, the timer keeps firing stall warnings during the idle gap.
            heartbeat.stop()
            executorLog.info(
              '[CLI:result-received] Turn complete — pausing stream read (ready for input)'
            )

            // Defensive drain: when a /goal was queued, race iterator.next() vs
            // 1.5s timer. If a trailing result arrives, consume + discard it.
            // If the timer wins, the pending .next() resolves on the next turn's
            // first message and is handled by the existing loop.
            if (goalWasQueued && this.ndjsonIterator) {
              const drainIterator = this.ndjsonIterator
              const drainTimer = new Promise<'timeout'>((resolve) =>
                setTimeout(() => resolve('timeout'), 1500)
              )
              const drainNext = drainIterator
                .next()
                .then((r) => ({ ...r, _source: 'iter' as const }))
              const drainResult = await Promise.race([drainNext, drainTimer])
              if (drainResult !== 'timeout' && !drainResult.done) {
                const trailingMsg = drainResult.value as Record<string, unknown>
                if (trailingMsg.type === 'result') {
                  executorLog.info('[CLI:goal] drained trailing goal result')
                } else {
                  // Not a result — unexpected. Log but don't re-process.
                  executorLog.warn(
                    `[CLI:goal] drained non-result message (type=${trailingMsg.type}) — discarded`
                  )
                }
              } else if (drainResult === 'timeout') {
                executorLog.debug(
                  '[CLI:goal] drain timer expired — no trailing result (will resolve on next turn)'
                )
              }
            }
            break
          }
        }
      } catch (error) {
        // Stream interrupted (abort, process kill, etc.)
        if ((error as NodeJS.ErrnoException).code !== 'ERR_STREAM_PREMATURE_CLOSE') {
          throw error
        }
        executorLog.info('[CLI:stream] Stream closed (process ended or aborted)')
        this.ndjsonIterator = null
      }
      executorLog.info(`[CLI:stream-end] Total NDJSON messages received: ${msgCount}`)

      // Detect CLI crash: process exited with non-zero code and produced no messages
      if (msgCount === 0 && this.lastExitCode !== null && this.lastExitCode !== 0) {
        const stderrHint = this.lastStderrError ? ` — ${this.lastStderrError}` : ''
        executorLog.error(
          `[CLI:crash-detected] CLI exited with code ${this.lastExitCode} before producing any output${stderrHint}`
        )
        const errorMsg = `CLI failed to start (exit code ${this.lastExitCode})${stderrHint}`
        telemetry.recordFailure(new Error(errorMsg))
        yield { type: 'error', error: errorMsg }
      }
    } catch (error) {
      executorLog.error('CLI execution error:', error)
      telemetry.recordFailure(error as Error)
      yield {
        type: 'error',
        error: `CLI execution failed: ${(error as Error).message}`
      }
    } finally {
      heartbeat.stop()
    }

    // Telemetry: finalize() is a no-op when recordFailure() was already called
    // (finalize only transitions from 'started' → 'succeeded').
    const tokenSummary = tokens.getSummary()
    telemetry.finalize(tokenSummary)

    // Zero-token detection: CLI produced text but reported 0 tokens (possible crash mid-stream)
    if (tokenSummary.input === 0 && tokenSummary.output === 0 && state.streamedTextLength > 0) {
      executorLog.warn(
        `[PIPELINE:zero-token-warning] CLI produced ${state.streamedTextLength} chars of text but reported 0 tokens — possible crash before result event`
      )
    }

    // Yield final metadata chunk (callers check for _meta)
    yield {
      type: 'status',
      content: 'complete',
      _meta: {
        sessionId: state.sessionId,
        result: state.resultText,
        terminalReason: state.terminalReason,
        sessionTitle: state.sessionTitle,
        resultOrigin: state.resultOrigin,
        tokenUsage: tokenSummary
      }
    } as StreamChunk & { _meta: CLIExecuteResult }
  }

  /**
   * Execute a single prompt and collect the full text result (non-streaming).
   * Used for decomposition and other one-shot queries.
   */
  async executeAndCollect(options: CLIExecuteOptions): Promise<{
    result: string
    sessionId?: string
    tokenUsage: { input: number; output: number }
  }> {
    let result = ''
    let sessionId: string | undefined
    const totalUsage = { input: 0, output: 0 }

    for await (const chunk of this.execute(options)) {
      if (chunk.type === 'text' && chunk.content) {
        result += chunk.content
      }
      if ('_meta' in chunk && chunk._meta) {
        const meta = chunk._meta as CLIExecuteResult
        sessionId = meta.sessionId
        totalUsage.input = meta.tokenUsage.input
        totalUsage.output = meta.tokenUsage.output
        if (!result && meta.result) {
          result = typeof meta.result === 'string' ? meta.result : JSON.stringify(meta.result)
        }
      }
    }

    return { result, sessionId, tokenUsage: totalUsage }
  }

  /**
   * Send a slash command to the interactive CLI (e.g. /compact, /clear).
   * Only works when a process is alive.
   */
  sendSlashCommand(command: string): void {
    if (!this.isAlive() || !this.cliProcess?.stdin) {
      executorLog.warn(`[CLI:slash] Cannot send "${command}" — no active process`)
      return
    }
    // EXEC-04: Reject embedded newlines to prevent command injection;
    // only accept /command [args] format on a single line
    const sanitized = command.split('\n')[0].trim()
    if (!/^\/[a-z_]+(\s+\S.*)?$/i.test(sanitized)) {
      executorLog.error(`[CLI:slash] Invalid command format: ${command.slice(0, 80)}`)
      return
    }
    executorLog.info(`[CLI:slash] Sending: ${sanitized}`)
    // EXEC-10: Wrap stdin.write in try-catch — throws if pipe is already closed
    try {
      this.cliProcess.stdin.write(sanitized + '\n')
    } catch (err) {
      executorLog.error(`[CLI:slash] stdin.write failed:`, err)
    }
  }

  /**
   * Send /compact to trigger context compaction via the interactive CLI.
   */
  compact(): void {
    this.sendSlashCommand('/compact')
  }

  /**
   * Change the CLI's permission mode mid-session via the control protocol.
   * Sends a set_permission_mode control_request to stdin.
   * Requires `--allow-dangerously-skip-permissions` to be present in the CLI args
   * for runtime elevation to 'bypassPermissions'.
   */
  setPermissionMode(
    mode: 'plan' | 'auto' | 'bypassPermissions' | 'default' | 'acceptEdits' | 'dontAsk'
  ): void {
    if (!this.isAlive() || !this.cliProcess?.stdin) {
      executorLog.warn('[CLI:setPermissionMode] Cannot set mode — no active process')
      return
    }
    const controlRequest = {
      type: 'control_request',
      request_id: `perm_${Date.now()}_${Math.random().toString(36).slice(2, 6)}`,
      request: {
        subtype: 'set_permission_mode',
        mode
      }
    }
    executorLog.info(`[CLI:setPermissionMode] Sending: ${mode}`)
    writeNdjsonMessage(this.cliProcess.stdin, controlRequest)
  }

  /**
   * Kill the active CLI process. SIGTERM first (closes stdout so any pending
   * iterator `.next()` settles), then close the async generator, then wait for
   * exit with a 5s SIGKILL escalation.
   *
   * DEADLOCK-FIX: Previously `iter.return()` was called BEFORE `proc.kill()`.
   * Async-generator semantics queue `.return()` behind a pending `.next()`,
   * which only settles when stdout closes — but `proc.kill()` (the thing that
   * closes stdout) was sequenced AFTER the await. This caused a permanent
   * deadlock when the CLI was idle after emitting a result.
   */
  async killProcess(): Promise<void> {
    if (!this.cliProcess) return

    const proc = this.cliProcess
    const iter = this.ndjsonIterator
    this.cliProcess = null
    // Unblock any in-flight read immediately — killProcess() awaits the
    // generator's return() below, which queues behind a pending next().
    this.disarmExitSignal('CLI process killed while awaiting output')
    this.ndjsonIterator = null
    this.cliReadyForInput = false

    // Step 1: Send SIGTERM first — this closes stdout, which lets any pending
    // iterator .next() settle so .return() can proceed.
    try {
      proc.kill('SIGTERM')
    } catch {
      // Already dead — fall through to cleanup
    }

    // Step 2: Close the async generator with a 2s timeout race.
    // After SIGTERM, stdout should close promptly letting .return() complete.
    if (iter) {
      try {
        const iterTimeout = new Promise<void>((r) => setTimeout(r, 2000))
        await Promise.race([iter.return?.(undefined), iterTimeout])
      } catch {
        /* ignore — process is dying */
      }
    }

    // Step 3: Wait for process exit with 5s SIGKILL escalation.
    return new Promise<void>((resolve) => {
      const forceKillTimer = setTimeout(() => {
        try {
          proc.kill('SIGKILL')
        } catch {
          // Already dead
        }
        this.cleanupSystemPromptFile()
        resolve()
      }, 5000)

      proc.once('exit', () => {
        clearTimeout(forceKillTimer)
        this.cleanupSystemPromptFile()
        resolve()
      })

      // If process already exited from SIGTERM, 'exit' fires immediately.
      // If not, forceKillTimer will escalate.
    })
  }

  // ── Private helpers ──

  /**
   * Spawn a fresh CLI process, wire abort/stderr/exit handlers, and write
   * the initial user message to stdin.
   * Extracted from execute() — cohesive process lifecycle setup concern.
   */
  private async spawnCLIProcess(options: CLIExecuteOptions): Promise<void> {
    // Kill any existing process BEFORE building args — killProcess() calls
    // cleanupSystemPromptFile() which deletes this.systemPromptFile.
    // If buildCLIArgs runs first, it writes a new prompt file that
    // killProcess then immediately deletes (race condition).
    await this.killProcess()

    const args = this.buildCLIArgs(options)
    const env = this.buildProcessEnv(options)

    executorLog.info(
      `[CLI:spawn] claude ${args.join(' ').replace(/--system-prompt ".*?"/, '--system-prompt "..."')}`
    )
    executorLog.info(`[CLI:args] ${args.join(' ')}`)

    // MCP diagnostic — surface config path and tool counts for debugging
    const mcpConfigIdx = args.indexOf('--mcp-config')
    const allowedToolsIdx = args.indexOf('--allowedTools')
    executorLog.info(
      `[CLI:mcp-diag] mcp-config=${mcpConfigIdx >= 0 ? args[mcpConfigIdx + 1] : 'NONE'} ` +
        `allowedToolsCount=${allowedToolsIdx >= 0 ? args[allowedToolsIdx + 1]?.split(',').length : 0} ` +
        `permissionMode=${args[args.indexOf('--permission-mode') + 1] ?? 'unset'}`
    )

    // EXEC-02: Guard spawn() — throws synchronously (ENOENT/ENOEXEC) if 'claude'
    // is not in PATH or is not a valid executable.
    try {
      this.cliProcess = spawn('claude', args, {
        cwd: options.cwd,
        env,
        stdio: ['pipe', 'pipe', 'pipe'],
        detached: false,
        windowsHide: true
      })
      // Arm before any handler can fire, so an immediate spawn failure still
      // has a signal to reject.
      this.armExitSignal()
    } catch (err) {
      this.cliProcess = null
      const code = (err as NodeJS.ErrnoException).code
      const message = (err as Error).message
      this.lastStderrError = `Failed to spawn claude CLI: ${message}`
      if (code === 'ENOEXEC') {
        throw new Error(
          `Resolved 'claude' is not executable (wrong arch/format or missing shebang). Details: ${message}`
        )
      }
      throw new Error(
        `Claude CLI not found — ensure 'claude' is installed and in PATH. Details: ${message}`
      )
    }

    // Wire abort controller to process kill
    if (options.abortController) {
      const signal = options.abortController.signal
      if (signal.aborted) {
        this.cliProcess.kill('SIGTERM')
      } else {
        signal.addEventListener(
          'abort',
          () => {
            this.killProcess()
          },
          { once: true }
        )
      }
    }

    // Log stderr — upgrade to ERROR level for patterns that indicate real failures
    this.cliProcess.stderr?.on('data', (data: Buffer) => {
      const text = data.toString('utf-8').trim()
      if (!text) return
      if (STDERR_ERROR_PATTERN.test(text)) {
        executorLog.error(`[CLI:stderr-ERROR] ${text.slice(0, 500)}`)
        this.lastStderrError = text.slice(0, 500)
      } else {
        executorLog.info(`[CLI:stderr] ${text.slice(0, 500)}`)
      }
    })

    // Handle process exit
    this.cliProcess.on('exit', (code, signal) => {
      executorLog.info(`[CLI:exit] code=${code} signal=${signal}`)
      this.lastExitCode = code
      // EXEC-03: Clean up temp system prompt file on natural exit/crash
      this.cleanupSystemPromptFile()
      const exited = this.cliProcess
      this.cliProcess = null
      // Break any in-flight read. 'exit' does not imply stdout has ended — an
      // inherited fd can hold it open — so destroying it is what actually lets
      // parseNdjsonStream's `for await` finish. The signal covers the case
      // where even that doesn't land.
      try {
        exited?.stdout?.destroy()
      } catch {
        /* already torn down */
      }
      this.disarmExitSignal(
        `CLI process exited (code=${code} signal=${signal}) while awaiting output`
      )
    })

    this.cliProcess.on('error', (err) => {
      executorLog.error('[CLI:error]', err)
      // EXEC-03: Clean up temp system prompt file on spawn error
      this.cleanupSystemPromptFile()
      this.cliProcess = null
      this.disarmExitSignal(`CLI process error while awaiting output: ${err.message}`)
    })

    // Write the initial user message to stdin
    if (this.cliProcess.stdin) {
      await this.writeToStdin(buildUserMessage(options.prompt))

      // Queue /goal as a second stdin message (spawn path) — enforce mode only
      const spawnGoalMode = options.goalMode ?? 'advisory'
      const goalCmd =
        options.goal && spawnGoalMode === 'enforce' ? buildGoalCommand(options.goal) : null
      if (goalCmd) {
        await this.writeToStdin(buildUserMessage(goalCmd))
        this.goalQueuedForTurn = true
        executorLog.info(`[CLI:goal] queued condition (${goalCmd.length} chars)`)
      } else {
        this.goalQueuedForTurn = false
      }
    }
  }

  /**
   * Write a message to stdin with backpressure handling.
   * If the kernel buffer is full, waits for 'drain' before resolving.
   * Ensures messages aren't silently dropped under heavy load.
   */
  private async writeToStdin(message: Record<string, unknown>): Promise<void> {
    if (!this.cliProcess?.stdin) {
      throw new Error('CLI stdin unavailable — process may have exited')
    }
    const accepted = writeNdjsonMessage(this.cliProcess.stdin, message)
    if (!accepted) {
      // stdin buffer is full — wait for it to drain before continuing.
      const stdin = this.cliProcess.stdin
      await new Promise<void>((resolve) => {
        let settled = false
        // Both paths must tear down the other, or a write that drains normally
        // leaves a 10s timer pinned and a 'drain' listener attached to a stream
        // that outlives this call — leaking a listener per backpressured write.
        const finish = (): void => {
          if (settled) return
          settled = true
          clearTimeout(safety)
          stdin.off('drain', finish)
          resolve()
        }
        // Safety: resolve after 10s if drain never fires (process may have died)
        const safety = setTimeout(() => {
          executorLog.warn('[CLI:stdin] drain never fired within 10s — continuing')
          finish()
        }, 10_000)
        stdin.once('drain', finish)
      })
    }
    this.cliReadyForInput = false
  }

  /**
   * Build CLI arguments from execute options.
   * Maps SDK-style options to their `claude` CLI flag equivalents.
   */
  private buildCLIArgs(options: CLIExecuteOptions): string[] {
    const args: string[] = [
      // Core interactive mode flags — stream-json enables NDJSON on stdout/stdin
      '--output-format',
      'stream-json',
      '--input-format',
      'stream-json',
      '--verbose',
      // Include partial messages for real-time streaming (same as SDK's includePartialMessages)
      '--include-partial-messages',
      // Allow runtime switch to bypassPermissions via set_permission_mode control request.
      // Without this flag, the CLI rejects mid-session elevation to bypassPermissions.
      '--allow-dangerously-skip-permissions'
    ]

    // Model
    if (options.model) {
      args.push('--model', options.model)
    }

    // Permission mode
    if (options.permissionMode) {
      // Map SDK permission modes to CLI equivalents.
      // The CLI's --permission-mode flag accepts the literal mode name.
      // Note: 'bypassPermissions' is the correct value (not 'dangerously-skip-permissions',
      // which is a standalone flag, not a --permission-mode value).
      const modeMap: Record<string, string> = {
        default: 'default',
        plan: 'plan',
        bypassPermissions: 'bypassPermissions',
        acceptEdits: 'acceptEdits',
        auto: 'auto',
        dontAsk: 'dontAsk'
      }
      const cliMode = modeMap[options.permissionMode] ?? 'default'
      args.push('--permission-mode', cliMode)
    }

    // System prompt — written to a temp file to avoid shell escaping issues
    // and OS arg-length limits (system prompts can be 15K-25K chars).
    if (options.systemPrompt) {
      let fullPrompt = options.systemPrompt

      // Goal — delivered via system prompt since the CLI has no --goal flag.
      // (/goal is a session-only slash command, not a CLI argument.)
      if (options.goal) {
        fullPrompt += `\n\n## Completion Goal\n\nWork autonomously until the following condition is met, then emit the completion block:\n\n${options.goal}`
      }

      const promptFilePath = this.writeSystemPromptFile(fullPrompt)
      args.push('--system-prompt-file', promptFilePath)
    }

    // Session resume — validate format before passing to CLI
    if (options.resume) {
      if (/^[a-zA-Z0-9_-]{8,}$/.test(options.resume)) {
        args.push('--resume', options.resume)
      } else {
        executorLog.warn(
          `[CLI:invalid-resume] Malformed session ID (skipping --resume): ${options.resume.slice(0, 30)}`
        )
      }
    }

    // Resume at specific message (undo support)
    if (options.resumeSessionAt) {
      args.push('--resume-session-at', options.resumeSessionAt)
    }

    // Max turns
    if (options.maxTurns) {
      args.push('--max-turns', String(options.maxTurns))
    }

    // MCP config path (external servers)
    if (options.mcpConfigPath) {
      args.push('--mcp-config', options.mcpConfigPath)
    }

    // Allowed tools
    if (options.allowedTools?.length) {
      args.push('--allowedTools', options.allowedTools.join(','))
    }

    // Disallowed tools
    if (options.disallowedTools?.length) {
      args.push('--disallowedTools', options.disallowedTools.join(','))
    }

    // Permission prompt tool — routes CLI permission requests to our MCP tool
    // instead of auto-denying. The control-actions server surfaces these in the UI.
    if (options.permissionPromptTool) {
      args.push('--permission-prompt-tool', options.permissionPromptTool)
    }

    // Additional directories
    if (options.additionalDirectories?.length) {
      for (const dir of options.additionalDirectories) {
        args.push('--add-dir', dir)
      }
    }

    // Effort level — Claude Code 2.1+ supports all 5 levels natively
    if (options.effort) {
      args.push('--effort', options.effort)
    }

    // Betas (1M context)
    if (options.betas?.length) {
      for (const beta of options.betas) {
        args.push('--betas', beta)
      }
    }

    // Fallback model
    if (options.fallbackModel) {
      args.push('--fallback-model', options.fallbackModel)
    }

    // Goal is delivered via system prompt (see above) for persistent visibility.
    // The /goal slash command is queued separately via stdin in spawnCLIProcess().
    // thinkingBudget is dropped silently (no CLI equivalent).

    return args
  }

  /**
   * Write a system prompt to a temp file. Uses content hashing to avoid
   * rewriting identical prompts (common on cache-hit turns via Strategy ζ).
   * Returns the absolute path to the file. The file is cleaned up when
   * the CLI process exits (via killProcess) or on the next call.
   */
  private writeSystemPromptFile(prompt: string): string {
    // Hash-based dedup: skip write if content hasn't changed and file still exists
    const hash = createHash('md5').update(prompt).digest('hex').slice(0, 12)
    if (
      hash === this.lastSystemPromptHash &&
      this.systemPromptFile &&
      existsSync(this.systemPromptFile)
    ) {
      return this.systemPromptFile
    }

    // Clean up previous file if content changed
    this.cleanupSystemPromptFile()

    const dir = join(tmpdir(), 'code-atelier-prompts')
    if (!existsSync(dir)) {
      mkdirSync(dir, { recursive: true })
    }
    const filePath = join(dir, `system-prompt-${Date.now()}-${randomUUID().slice(0, 8)}.md`)
    writeFileSync(filePath, prompt, 'utf-8')
    this.systemPromptFile = filePath
    this.lastSystemPromptHash = hash
    return filePath
  }

  /**
   * Remove the current system prompt temp file.
   */
  private cleanupSystemPromptFile(): void {
    if (this.systemPromptFile) {
      try {
        unlinkSync(this.systemPromptFile)
      } catch {
        // Non-fatal — file may already be gone
      }
      this.systemPromptFile = null
      this.lastSystemPromptHash = null
    }
  }

  /**
   * Build the process environment.
   * Includes current env + any user-provided overrides + app identification.
   */
  private buildProcessEnv(options: CLIExecuteOptions): Record<string, string | undefined> {
    return {
      ...buildEnvWithPath(),
      ...(options.envOverrides ?? {}),
      CLAUDE_AGENT_SDK_CLIENT_APP: `code-atelier/${app.getVersion()}`,
      CLAUDE_CODE_SUPPRESS_SESSION_ATTRIBUTION: '1'
    }
  }
}

// ── Goal command builder ──

/**
 * Build a sanitized `/goal` slash command string from a raw condition.
 *
 * - Collapses newlines/whitespace to single spaces, trims.
 * - Returns `null` for empty/whitespace-only input.
 * - Prefix-guards against clear-alias words that the CLI interprets as
 *   subcommands (`/goal clear`, `/goal stop`, etc.) by wrapping with
 *   "Condition: " prefix.
 * - Caps at `GOAL_MAX_CHARS` (4,000) — truncates with a log warning.
 *
 * Exported for testing.
 */
export function buildGoalCommand(goal: string): string | null {
  // Collapse newlines and whitespace to single spaces
  const sanitized = goal.replace(/\s+/g, ' ').trim()
  if (!sanitized) return null

  // Prefix-guard: if the condition text starts with a word the CLI would
  // interpret as a clear/cancel subcommand, wrap it so it's unambiguous.
  let conditionText = sanitized
  if (GOAL_CLEAR_ALIASES.test(conditionText)) {
    conditionText = `Condition: ${conditionText}`
  }

  // Truncate if over the cap
  if (conditionText.length > GOAL_MAX_CHARS) {
    executorLog.warn(
      `[CLI:goal] condition truncated from ${conditionText.length} to ${GOAL_MAX_CHARS} chars`
    )
    conditionText = conditionText.slice(0, GOAL_MAX_CHARS)
  }

  return `/goal ${conditionText}`
}

/**
 * Sweep stale system-prompt temp files from /tmp/code-atelier-prompts/.
 * Removes files older than 24 hours. Call on app startup to prevent
 * accumulation from crashes that skip normal cleanup.
 */
export function cleanupStalePromptFiles(): void {
  const dir = join(tmpdir(), 'code-atelier-prompts')
  if (!existsSync(dir)) return

  const MAX_AGE_MS = 24 * 60 * 60_000 // 24 hours
  const now = Date.now()
  let removed = 0

  try {
    for (const file of readdirSync(dir)) {
      const filePath = join(dir, file)
      try {
        const stat = statSync(filePath)
        if (now - stat.mtimeMs > MAX_AGE_MS) {
          unlinkSync(filePath)
          removed++
        }
      } catch {
        // Non-fatal — skip individual files that can't be stat'd/removed
      }
    }
    if (removed > 0) {
      executorLog.info(`[CLI:cleanup] Removed ${removed} stale prompt file(s) from ${dir}`)
    }
  } catch {
    // Non-fatal — directory access issues
  }
}
