import log from 'electron-log/main'
import { basename, dirname } from 'node:path'

// ── Types ──

export interface RawChunk {
  id: string
  filePath: string
  symbolName: string
  symbolKind: 'function' | 'method' | 'class' | 'interface' | 'type' | 'enum' | 'const'
  body: string
  startLine: number
  endLine: number
  signature: string
  isPublic: boolean
  isAsync: boolean
  isStatic: boolean
  isAbstract: boolean
  language: string
}

export interface ScopeContext {
  className: string
  classKind: 'class' | 'interface' | 'abstract class' | 'record'
  classSignature: string
  classDecorators: string[]
  parentClassImports: string[]
  siblingMethodSignatures: string[]
}

export interface ChunkMetadata {
  filePath: string
  fileName: string
  directory: string
  projectName: string
  symbolName: string
  symbolKind: string
  className: string | null
  signature: string
  startLine: number
  endLine: number
  language: string
  isPublic: boolean
  isAsync: boolean
  isStatic: boolean
  isAbstract: boolean
  hasTests: boolean
  importedBy: string[]
  pageRank: number
  hasDocstring: boolean
  lineCount: number
  hasDescription: boolean
  lastModified: number
  indexedAt: number
}

export interface ProcessedChunk {
  id: string
  embedText: string
  body: string
  metadata: ChunkMetadata
}

export interface PreprocessingOptions {
  generateDescriptions: boolean
  descriptionModel: string
  maxChunkLines: number
  overlapLines: number
  skipPatterns: string[]
  includePrivateMethods: boolean
  includeSiblingSignatures: boolean
  paused: boolean
  cancelled: boolean
}

export const DEFAULT_PREPROCESSING_OPTIONS: PreprocessingOptions = {
  generateDescriptions: false,
  descriptionModel: 'claude-haiku-4-5-20251001',
  maxChunkLines: 80,
  overlapLines: 5,
  skipPatterns: [],
  includePrivateMethods: true,
  includeSiblingSignatures: true,
  paused: false,
  cancelled: false
}

// ── Stage 1: Noise filtering ──

const SKIP_PATTERNS = [
  // Package managers
  '**/node_modules/**',
  '**/vendor/**',
  '**/.pnp/**',

  // Build output
  '**/dist/**',
  '**/build/**',
  '**/out/**',
  '**/.next/**',
  '**/bin/**',
  '**/obj/**',

  // Generated files
  '**/*.generated.ts',
  '**/*.generated.cs',
  '**/*.g.cs',
  '**/*.g.tsx',
  '**/*.designer.cs',
  '**/migrations/**',
  '**/*.pb.ts',
  '**/*.pb.cs',

  // Minified / compiled
  '**/*.min.js',
  '**/*.min.css',
  '**/*.bundle.js',
  '**/*.chunk.js',

  // Lock files and configs with no semantic content
  '**/package-lock.json',
  '**/yarn.lock',
  '**/pnpm-lock.yaml',

  // Test snapshots
  '**/__snapshots__/**',
  '**/*.snap',

  // Assets
  '**/*.svg',
  '**/*.png',
  '**/*.jpg',
  '**/*.ico',
  '**/*.woff',
  '**/*.ttf'
]

/**
 * Check if a file path matches any of the skip patterns using simple glob matching.
 * Patterns use ** for any path segment(s) and * for any non-/ characters.
 */
function matchesSkipPattern(filePath: string, patterns: string[]): boolean {
  const normalized = filePath.replace(/\\/g, '/')
  for (const pattern of patterns) {
    // Convert glob to regex using placeholder to avoid double-replacement
    const regexStr = pattern
      .replace(/\*\*/g, '\0GLOBSTAR\0')   // placeholder for **
      .replace(/\*/g, '[^/]*')            // * → non-slash chars
      .replace(/\./g, '\\.')              // escape dots
      .replace(/\0GLOBSTAR\0\//g, '(?:.+/)?')  // **/ → optional prefix ending in /
      .replace(/\/\0GLOBSTAR\0/g, '(?:/.+)?')  // /** → optional suffix starting with /
      .replace(/\0GLOBSTAR\0/g, '.*')          // ** standalone → anything
    if (new RegExp(`^${regexStr}$`).test(normalized)) {
      return true
    }
  }
  return false
}

/**
 * Stage 1: Determine if a file should be skipped from indexing.
 * Checks path-based patterns and content-based heuristics.
 */
export function shouldSkipFile(
  filePath: string,
  content: string,
  extraPatterns: string[] = []
): boolean {
  // Path-based filtering
  const allPatterns = [...SKIP_PATTERNS, ...extraPatterns]
  if (matchesSkipPattern(filePath, allPatterns)) {
    return true
  }

  // Content-based filtering: auto-generated files
  const firstLines = content.slice(0, 500).toLowerCase()
  if (
    firstLines.includes('auto-generated') ||
    firstLines.includes('this file is automatically generated') ||
    firstLines.includes('do not edit') ||
    firstLines.includes('generated by') ||
    firstLines.includes('@generated') ||
    firstLines.includes('<auto-generated>')
  ) {
    return true
  }

  // Skip minified files (very long lines, no newlines)
  const lines = content.split('\n')
  const avgLineLength = content.length / Math.max(lines.length, 1)
  if (avgLineLength > 500) {
    return true
  }

  // Skip files with almost no alphanumeric content (binary-ish)
  const alphanumCount = (content.match(/[a-zA-Z0-9]/g) ?? []).length
  const alphanumRatio = alphanumCount / Math.max(content.length, 1)
  if (alphanumRatio < 0.3) {
    return true
  }

  return false
}

// ── Stage 2: Context injection ──

/**
 * Extract relevant import names from file content that are used in a chunk.
 * Uses regex-based extraction (not AST — good enough for headers).
 */
export function extractRelevantImports(fileContent: string, chunk: RawChunk): string[] {
  const imports: string[] = []

  // Match ES import statements: import { X, Y } from 'module'
  const esImportRegex = /import\s+(?:type\s+)?{([^}]+)}\s+from\s+['"]([^'"]+)['"]/g
  // Match default imports: import X from 'module'
  const defaultImportRegex = /import\s+(?:type\s+)?(\w+)\s+from\s+['"]([^'"]+)['"]/g
  // Match C# using: using Namespace.Type;
  const csharpUsingRegex = /using\s+([\w.]+)\s*;/g

  const allImportedNames: { name: string; module: string }[] = []

  let match: RegExpExecArray | null
  while ((match = esImportRegex.exec(fileContent)) !== null) {
    const names = match[1].split(',').map((n) => n.trim().split(/\s+as\s+/).pop()!.trim())
    const module = match[2]
    for (const name of names) {
      if (name) allImportedNames.push({ name, module })
    }
  }

  while ((match = defaultImportRegex.exec(fileContent)) !== null) {
    allImportedNames.push({ name: match[1], module: match[2] })
  }

  while ((match = csharpUsingRegex.exec(fileContent)) !== null) {
    const parts = match[1].split('.')
    allImportedNames.push({ name: parts[parts.length - 1], module: match[1] })
  }

  // Filter to imports actually referenced in the chunk body
  for (const imp of allImportedNames) {
    if (chunk.body.includes(imp.name)) {
      imports.push(imp.name)
    }
  }

  return [...new Set(imports)].slice(0, 8)
}

/**
 * Stage 2: Build a structured header to prepend to the chunk for embedding.
 */
export function buildChunkHeader(
  chunk: RawChunk & { imports: string[]; className?: string | null }
): string {
  const parts: string[] = []

  // File path (last 3 segments to keep it concise)
  const shortPath = chunk.filePath.split('/').slice(-3).join('/')
  parts.push(`# File: ${shortPath}`)

  // Language
  parts.push(`# Language: ${chunk.language}`)

  // Scope chain (e.g. "UserService > validateJwt")
  if (chunk.className) {
    parts.push(`# Scope: ${chunk.className} > ${chunk.symbolName}`)
  } else {
    parts.push(`# Scope: ${chunk.symbolName}`)
  }

  // Symbol kind and visibility
  const visibility = chunk.isPublic ? 'public' : 'private'
  parts.push(`# Kind: ${visibility} ${chunk.symbolKind}`)

  // Full signature
  parts.push(`# Signature: ${chunk.signature}`)

  // Key imports used by this chunk
  if (chunk.imports.length > 0) {
    parts.push(`# Uses: ${chunk.imports.join(', ')}`)
  }

  // Blank line separator before code
  parts.push('')

  return parts.join('\n')
}

/**
 * Stage 2: Build the full embed text (header + body).
 */
export function buildEmbedText(
  chunk: RawChunk & { imports: string[]; className?: string | null }
): string {
  return buildChunkHeader(chunk) + chunk.body
}

// ── Stage 3: Scope enrichment ──

/**
 * Stage 3: Build scope contexts for all classes in a file.
 * Groups methods by their parent class and collects sibling signatures.
 */
export function buildScopeContexts(fileTags: RawChunk[]): Map<string, ScopeContext> {
  const contexts = new Map<string, ScopeContext>()

  // Find all classes/interfaces
  const classChunks = fileTags.filter(
    (t) => t.symbolKind === 'class' || t.symbolKind === 'interface'
  )

  for (const cls of classChunks) {
    // Find methods that belong to this class (by line range)
    const methods = fileTags.filter(
      (t) =>
        t.symbolKind === 'method' &&
        t.startLine >= cls.startLine &&
        t.endLine <= cls.endLine
    )

    // Extract decorators from the class body
    const decorators: string[] = []
    const decoratorRegex = /@(\w+)\([^)]*\)/g
    const classHeader = cls.body.split('{')[0] ?? ''
    let match: RegExpExecArray | null
    while ((match = decoratorRegex.exec(classHeader)) !== null) {
      decorators.push(match[0])
    }

    // Determine class kind
    let classKind: ScopeContext['classKind'] = 'class'
    if (cls.symbolKind === 'interface') {
      classKind = 'interface'
    } else if (cls.signature.includes('abstract')) {
      classKind = 'abstract class'
    } else if (cls.signature.includes('record')) {
      classKind = 'record'
    }

    const siblingSignatures = methods
      .filter((m) => m.isPublic)
      .map((m) => m.signature)

    contexts.set(cls.symbolName, {
      className: cls.symbolName,
      classKind,
      classSignature: cls.signature,
      classDecorators: decorators,
      parentClassImports: [],
      siblingMethodSignatures: siblingSignatures
    })
  }

  return contexts
}

/**
 * Stage 3: Build scope-enriched text to prepend for methods in classes.
 */
export function buildScopeHeader(scope: ScopeContext, includeSiblings: boolean): string {
  const parts: string[] = []
  parts.push(`# Class: ${scope.classSignature}`)

  if (scope.classDecorators.length > 0) {
    parts.push(`# Class decorators: ${scope.classDecorators.join(', ')}`)
  }

  if (includeSiblings && scope.siblingMethodSignatures.length > 0) {
    // Show only method names for brevity
    const shortSigs = scope.siblingMethodSignatures.map((s) => {
      const nameMatch = s.match(/(\w+)\s*\(/)
      return nameMatch ? `${nameMatch[1]}()` : s
    })
    parts.push(`# Other public methods: ${shortSigs.join(', ')}`)
  }

  return parts.join('\n') + '\n'
}

// ── Stage 5: Metadata enrichment ──

/**
 * Stage 5: Build structured metadata for ChromaDB filtered queries.
 */
export function buildMetadata(
  chunk: RawChunk,
  scope: ScopeContext | null,
  projectName: string,
  hasDescription: boolean = false
): ChunkMetadata {
  // Detect if test file exists
  const hasTests =
    chunk.filePath.includes('.test.') ||
    chunk.filePath.includes('.spec.') ||
    chunk.filePath.includes('__tests__')

  // Detect docstring
  const hasDocstring =
    chunk.body.includes('/**') ||
    chunk.body.includes('///') ||
    chunk.body.includes('/// <summary>')

  const lines = chunk.body.split('\n')

  return {
    filePath: chunk.filePath,
    fileName: basename(chunk.filePath),
    directory: dirname(chunk.filePath),
    projectName,
    symbolName: chunk.symbolName,
    symbolKind: chunk.symbolKind,
    className: scope?.className ?? null,
    signature: chunk.signature,
    startLine: chunk.startLine,
    endLine: chunk.endLine,
    language: chunk.language,
    isPublic: chunk.isPublic,
    isAsync: chunk.isAsync,
    isStatic: chunk.isStatic,
    isAbstract: chunk.isAbstract,
    hasTests,
    importedBy: [],
    pageRank: 0,
    hasDocstring,
    lineCount: lines.length,
    hasDescription,
    lastModified: Date.now(),
    indexedAt: Date.now()
  }
}

// ── Stage 6: Overlap handling ──

/**
 * Stage 6: Split a chunk that exceeds maxLines with overlapping boundaries.
 */
export function splitLongChunk(
  chunk: ProcessedChunk,
  maxLines: number,
  overlapLines: number
): ProcessedChunk[] {
  const lines = chunk.body.split('\n')
  if (lines.length <= maxLines) return [chunk]

  const parts: ProcessedChunk[] = []
  let start = 0
  let partIndex = 0
  const totalParts = Math.ceil(lines.length / maxLines)

  while (start < lines.length) {
    const end = Math.min(start + maxLines, lines.length)
    const overlap = start > 0 ? lines.slice(start - overlapLines, start) : []
    const partBody = [...overlap, ...lines.slice(start, end)].join('\n')

    const partSymbolName = `${chunk.metadata.symbolName} (part ${partIndex + 1}/${totalParts})`

    parts.push({
      id: `${chunk.id}::part${partIndex}`,
      embedText: chunk.embedText, // Will be rebuilt with updated body
      body: partBody,
      metadata: {
        ...chunk.metadata,
        symbolName: partSymbolName,
        startLine: chunk.metadata.startLine + start - (start > 0 ? overlapLines : 0),
        endLine: chunk.metadata.startLine + end,
        lineCount: partBody.split('\n').length
      }
    })

    start = end
    partIndex++
  }

  return parts
}

// ── Full pipeline ──

/**
 * Process a single raw chunk through all preprocessing stages.
 * Returns null if the chunk should be skipped.
 */
export function preprocessChunk(
  rawChunk: RawChunk,
  fileContent: string,
  scopeContext: ScopeContext | null,
  projectName: string,
  options: PreprocessingOptions,
  description?: string
): ProcessedChunk[] | null {
  // Skip private methods if configured
  if (!options.includePrivateMethods && !rawChunk.isPublic && rawChunk.symbolKind === 'method') {
    return null
  }

  // Stage 2: Context injection
  const imports = extractRelevantImports(fileContent, rawChunk)
  const chunkWithImports = {
    ...rawChunk,
    imports,
    className: scopeContext?.className ?? null
  }

  let embedText = ''

  // Stage 4: Prepend description if available
  if (description) {
    embedText += description + '\n'
  }

  // Stage 3: Scope enrichment
  if (scopeContext && rawChunk.symbolKind === 'method') {
    embedText += buildScopeHeader(scopeContext, options.includeSiblingSignatures)
  }

  // Stage 2: Header + body
  embedText += buildEmbedText(chunkWithImports)

  // Stage 5: Metadata enrichment
  const metadata = buildMetadata(rawChunk, scopeContext, projectName, !!description)

  const processed: ProcessedChunk = {
    id: rawChunk.id,
    embedText,
    body: rawChunk.body,
    metadata
  }

  // Stage 6: Overlap handling
  const chunks = splitLongChunk(processed, options.maxChunkLines, options.overlapLines)

  // Rebuild embedText for split chunks
  if (chunks.length > 1) {
    for (const chunk of chunks) {
      // Rebuild header for each part with its updated symbolName
      const partChunk = {
        ...rawChunk,
        imports,
        className: scopeContext?.className ?? null,
        symbolName: chunk.metadata.symbolName
      }
      let partEmbedText = ''
      if (description) partEmbedText += description + '\n'
      if (scopeContext && rawChunk.symbolKind === 'method') {
        partEmbedText += buildScopeHeader(scopeContext, options.includeSiblingSignatures)
      }
      partEmbedText += buildChunkHeader(partChunk) + chunk.body
      chunk.embedText = partEmbedText
    }
  }

  return chunks
}

/** Split an array into chunks of a given size. */
function chunkArray<T>(arr: T[], size: number): T[][] {
  const result: T[][] = []
  for (let i = 0; i < arr.length; i += size) {
    result.push(arr.slice(i, i + size))
  }
  return result
}

/** Find the scope context for a chunk based on its symbol kind. */
function findScopeContext(
  rawChunk: RawChunk,
  scopeContexts: Map<string, ScopeContext>
): ScopeContext | null {
  if (rawChunk.symbolKind !== 'method') return null
  for (const [className, ctx] of scopeContexts) {
    if (
      ctx.siblingMethodSignatures.some((sig) => sig.includes(rawChunk.symbolName)) ||
      className === rawChunk.symbolName
    ) {
      return ctx
    }
  }
  return null
}

/** Batch size for grouping symbols in a single CLI call. */
const DESCRIPTION_BATCH_SIZE = 8

/** Number of concurrent CLI calls for batch description generation. */
const DESCRIPTION_CONCURRENCY = 3

export interface DescriptionProgressUpdate {
  descriptionsProcessed: number
  descriptionsTotal: number
  descriptionsCached: number
  descriptionsGenerated: number
}

/**
 * Run the full preprocessing pipeline over a set of raw chunks.
 *
 * When AI descriptions are enabled, uses a 3-phase approach:
 *   Phase 1 — Fast scan: collect all chunks needing descriptions, build embed text
 *   Phase 2 — Batch AI descriptions: generate in batches of 8 with 3 concurrent CLI calls
 *   Phase 3 — Preprocess: apply descriptions + metadata (all sync, fast)
 *
 * Calls onProgress at each file boundary and onDescriptionProgress during Phase 2.
 */
export async function runPreprocessingPipeline(
  tags: RawChunk[],
  fileContents: Map<string, string>,
  projectName: string,
  options: PreprocessingOptions,
  onProgress: (update: {
    processedFiles: number
    totalFiles: number
    processedChunks: number
    totalChunks: number
    skippedFiles: number
    currentFile: string
  }) => void,
  getDescription?: (chunk: RawChunk, embedText: string) => Promise<string | undefined>,
  getBatchDescriptions?: (
    chunks: Array<{ chunk: RawChunk; embedText: string }>
  ) => Promise<{ descriptions: Map<number, string>; cached: number; generated: number }>,
  onDescriptionProgress?: (update: DescriptionProgressUpdate) => void
): Promise<ProcessedChunk[]> {
  const results: ProcessedChunk[] = []

  // Group tags by file
  const fileGroups = new Map<string, RawChunk[]>()
  for (const tag of tags) {
    const group = fileGroups.get(tag.filePath) ?? []
    group.push(tag)
    fileGroups.set(tag.filePath, group)
  }

  const totalFiles = fileGroups.size
  let processedFiles = 0
  let processedChunks = 0
  let skippedFiles = 0

  // Pre-compute scope contexts and filter out skipped files (used in all phases)
  const validFiles: Array<{
    filePath: string
    fileTags: RawChunk[]
    content: string
    scopeContexts: Map<string, ScopeContext>
  }> = []

  for (const [filePath, fileTags] of fileGroups) {
    const content = fileContents.get(filePath)
    if (!content) {
      skippedFiles++
      processedFiles++
      continue
    }
    if (shouldSkipFile(filePath, content, options.skipPatterns)) {
      skippedFiles++
      processedFiles++
      onProgress({
        processedFiles,
        totalFiles,
        processedChunks,
        totalChunks: tags.length,
        skippedFiles,
        currentFile: filePath
      })
      continue
    }
    const scopeContexts = buildScopeContexts(fileTags)
    validFiles.push({ filePath, fileTags, content, scopeContexts })
  }

  // ── Phase 1+2: Batch AI descriptions (only when enabled + batch callback available) ──
  const descriptionMap = new Map<string, string>() // chunkId → description

  if (options.generateDescriptions && getBatchDescriptions) {
    // Phase 1: Collect all chunks that need descriptions (fast)
    const allChunksForDesc: Array<{
      chunkId: string
      chunk: RawChunk
      embedText: string
    }> = []

    for (const { fileTags, content, scopeContexts } of validFiles) {
      for (const rawChunk of fileTags) {
        const scopeContext = findScopeContext(rawChunk, scopeContexts)
        const imports = extractRelevantImports(content, rawChunk)
        const tempEmbedText = buildEmbedText({
          ...rawChunk,
          imports,
          className: scopeContext?.className ?? null
        })
        allChunksForDesc.push({
          chunkId: rawChunk.id,
          chunk: rawChunk,
          embedText: tempEmbedText
        })
      }
    }

    const descriptionsTotal = allChunksForDesc.length
    let descriptionsProcessed = 0
    let totalCached = 0
    let totalGenerated = 0

    onDescriptionProgress?.({
      descriptionsProcessed: 0,
      descriptionsTotal,
      descriptionsCached: 0,
      descriptionsGenerated: 0
    })

    // Phase 2: Batch generate descriptions with limited concurrency
    const batches = chunkArray(allChunksForDesc, DESCRIPTION_BATCH_SIZE)

    for (let i = 0; i < batches.length; i += DESCRIPTION_CONCURRENCY) {
      if (options.cancelled) break

      // Wait while paused
      while (options.paused && !options.cancelled) {
        await new Promise((resolve) => setTimeout(resolve, 500))
      }
      if (options.cancelled) break

      const concurrentBatches = batches.slice(i, i + DESCRIPTION_CONCURRENCY)
      const batchPromises = concurrentBatches.map((batch) =>
        getBatchDescriptions(batch.map((b) => ({ chunk: b.chunk, embedText: b.embedText })))
      )

      const batchResults = await Promise.all(batchPromises)

      // Map results back to chunk IDs
      for (let bIdx = 0; bIdx < concurrentBatches.length; bIdx++) {
        const batch = concurrentBatches[bIdx]
        const result = batchResults[bIdx]

        for (const [itemIdx, desc] of result.descriptions) {
          descriptionMap.set(batch[itemIdx].chunkId, desc)
        }

        descriptionsProcessed += batch.length
        totalCached += result.cached
        totalGenerated += result.generated
      }

      onDescriptionProgress?.({
        descriptionsProcessed,
        descriptionsTotal,
        descriptionsCached: totalCached,
        descriptionsGenerated: totalGenerated
      })
    }

    log.info(
      `[Preprocessing] AI descriptions: ${totalGenerated} generated, ${totalCached} cached, ${descriptionsTotal} total`
    )
  }

  // ── Phase 3: Preprocess all chunks (fast — descriptions already resolved) ──
  for (const { filePath, fileTags, content, scopeContexts } of validFiles) {
    if (options.cancelled) {
      log.info('[Preprocessing] Cancelled by user')
      break
    }

    // Wait while paused
    while (options.paused && !options.cancelled) {
      await new Promise((resolve) => setTimeout(resolve, 500))
    }

    for (const rawChunk of fileTags) {
      if (options.cancelled) break

      const scopeContext = findScopeContext(rawChunk, scopeContexts)

      // Look up pre-generated description, or fall back to single-call if no batch
      let description: string | undefined = descriptionMap.get(rawChunk.id)
      if (!description && options.generateDescriptions && getDescription && !getBatchDescriptions) {
        try {
          const imports = extractRelevantImports(content, rawChunk)
          const tempEmbedText = buildEmbedText({
            ...rawChunk,
            imports,
            className: scopeContext?.className ?? null
          })
          description = await getDescription(rawChunk, tempEmbedText)
        } catch (error) {
          log.warn(`[Preprocessing] Description generation failed for ${rawChunk.id}:`, error)
        }
      }

      const processed = preprocessChunk(
        rawChunk,
        content,
        scopeContext,
        projectName,
        options,
        description
      )

      if (processed) {
        results.push(...processed)
      }

      processedChunks++
    }

    processedFiles++
    onProgress({
      processedFiles,
      totalFiles,
      processedChunks,
      totalChunks: tags.length,
      skippedFiles,
      currentFile: filePath
    })
  }

  log.info(
    `[Preprocessing] Complete: ${results.length} chunks from ${processedFiles} files (${skippedFiles} skipped)`
  )

  return results
}
