/**
 * Stage 1: Noise filtering utilities for the preprocessing pipeline.
 *
 * Extracted from preprocessing.service.ts — purely functional,
 * no class dependencies.
 */

// ── Skip Patterns ──

export const SKIP_PATTERNS = [
  // Package managers
  '**/node_modules/**',
  '**/vendor/**',
  '**/.pnp/**',

  // Build output
  '**/dist/**',
  '**/build/**',
  '**/out/**',
  '**/.next/**',
  '**/bin/**',
  '**/obj/**',

  // Generated files
  '**/*.generated.ts',
  '**/*.generated.cs',
  '**/*.g.cs',
  '**/*.g.tsx',
  '**/*.designer.cs',
  '**/migrations/**',
  '**/*.pb.ts',
  '**/*.pb.cs',

  // Minified / compiled
  '**/*.min.js',
  '**/*.min.css',
  '**/*.bundle.js',
  '**/*.chunk.js',

  // Lock files and configs with no semantic content
  '**/package-lock.json',
  '**/yarn.lock',
  '**/pnpm-lock.yaml',

  // Test snapshots
  '**/__snapshots__/**',
  '**/*.snap',

  // Assets
  '**/*.svg',
  '**/*.png',
  '**/*.jpg',
  '**/*.ico',
  '**/*.woff',
  '**/*.ttf'
]

/**
 * Check if a file path matches any of the skip patterns using simple glob matching.
 * Patterns use ** for any path segment(s) and * for any non-/ characters.
 */
export function matchesSkipPattern(filePath: string, patterns: string[]): boolean {
  const normalized = filePath.replace(/\\/g, '/')
  for (const pattern of patterns) {
    // Convert glob to regex using placeholder to avoid double-replacement
    const regexStr = pattern
      .replace(/\*\*/g, '\0GLOBSTAR\0') // placeholder for **
      .replace(/\*/g, '[^/]*') // * → non-slash chars
      .replace(/\./g, '\\.') // escape dots
      .replace(/\0GLOBSTAR\0\//g, '(?:.+/)?') // **/ → optional prefix ending in /
      .replace(/\/\0GLOBSTAR\0/g, '(?:/.+)?') // /** → optional suffix starting with /
      .replace(/\0GLOBSTAR\0/g, '.*') // ** standalone → anything
    if (new RegExp(`^${regexStr}$`).test(normalized)) {
      return true
    }
  }
  return false
}

/**
 * Stage 1: Determine if a file should be skipped from indexing.
 * Checks path-based patterns and content-based heuristics.
 */
export function shouldSkipFile(
  filePath: string,
  content: string,
  extraPatterns: string[] = []
): boolean {
  // Path-based filtering
  const allPatterns = [...SKIP_PATTERNS, ...extraPatterns]
  if (matchesSkipPattern(filePath, allPatterns)) {
    return true
  }

  // Content-based filtering: auto-generated files
  const firstLines = content.slice(0, 500).toLowerCase()
  if (
    firstLines.includes('auto-generated') ||
    firstLines.includes('this file is automatically generated') ||
    firstLines.includes('do not edit') ||
    firstLines.includes('generated by') ||
    firstLines.includes('@generated') ||
    firstLines.includes('<auto-generated>')
  ) {
    return true
  }

  // Skip minified files (very long lines, no newlines)
  const lines = content.split('\n')
  const avgLineLength = content.length / Math.max(lines.length, 1)
  if (avgLineLength > 500) {
    return true
  }

  // Skip files with almost no alphanumeric content (binary-ish)
  const alphanumCount = (content.match(/[a-zA-Z0-9]/g) ?? []).length
  const alphanumRatio = alphanumCount / Math.max(content.length, 1)
  if (alphanumRatio < 0.3) {
    return true
  }

  return false
}
