/**
 * Stage 1: Noise filtering utilities for the preprocessing pipeline.
 *
 * Extracted from preprocessing.service.ts — purely functional,
 * no class dependencies.
 */

import { excludedDirGlobs, matchesSkipPattern } from '../code-graph-exclusions'

// Re-exported so existing importers of this module keep working.
export { matchesSkipPattern }

// ── Skip Patterns ──

export const SKIP_PATTERNS = [
  // Directory exclusions derived from the shared source of truth
  // (ADDITIONAL_EXCLUDED_DIRS) so the code graph and the embedding pipeline
  // can never drift apart again. Covers bin, obj, packages, BuildSystem,
  // Tools, ThirdParty, NuGet, .vs, artifacts, publish, Debug, Release, etc.
  ...excludedDirGlobs(),

  // Package managers
  '**/node_modules/**',
  '**/vendor/**',
  '**/.pnp/**',

  // Build output not covered by the shared directory set
  '**/dist/**',
  '**/build/**',
  '**/.next/**',

  // Generated files
  '**/*.generated.ts',
  '**/*.generated.cs',
  '**/*.g.cs',
  '**/*.g.tsx',
  '**/*.designer.cs',
  '**/migrations/**',
  '**/*.pb.ts',
  '**/*.pb.cs',

  // Minified / compiled
  '**/*.min.js',
  '**/*.min.css',
  '**/*.bundle.js',
  '**/*.chunk.js',

  // Lock files and configs with no semantic content
  '**/package-lock.json',
  '**/yarn.lock',
  '**/pnpm-lock.yaml',

  // Test snapshots
  '**/__snapshots__/**',
  '**/*.snap',

  // Assets
  '**/*.svg',
  '**/*.png',
  '**/*.jpg',
  '**/*.ico',
  '**/*.woff',
  '**/*.ttf'
]

// matchesSkipPattern now lives in ../code-graph-exclusions (single source of
// truth shared with the code graph indexer) and is re-exported above.

/**
 * Stage 1: Determine if a file should be skipped from indexing.
 * Checks path-based patterns and content-based heuristics.
 */
export function shouldSkipFile(
  filePath: string,
  content: string,
  extraPatterns: string[] = []
): boolean {
  // Path-based filtering
  const allPatterns = [...SKIP_PATTERNS, ...extraPatterns]
  if (matchesSkipPattern(filePath, allPatterns)) {
    return true
  }

  // Content-based filtering: auto-generated files
  const firstLines = content.slice(0, 500).toLowerCase()
  if (
    firstLines.includes('auto-generated') ||
    firstLines.includes('this file is automatically generated') ||
    firstLines.includes('do not edit') ||
    firstLines.includes('generated by') ||
    firstLines.includes('@generated') ||
    firstLines.includes('<auto-generated>')
  ) {
    return true
  }

  // Skip minified files (very long lines, no newlines)
  const lines = content.split('\n')
  const avgLineLength = content.length / Math.max(lines.length, 1)
  if (avgLineLength > 500) {
    return true
  }

  // Skip files with almost no alphanumeric content (binary-ish)
  const alphanumCount = (content.match(/[a-zA-Z0-9]/g) ?? []).length
  const alphanumRatio = alphanumCount / Math.max(content.length, 1)
  if (alphanumRatio < 0.3) {
    return true
  }

  return false
}
