// AUTO-GENERATED by scripts/generate-sprite-catalog.ts
// Do not edit manually.

export interface PixelSpriteEntry {
  id: string
  category: 'male' | 'female' | 'soldier' | 'enemy' | 'other' | 'xmas'
  label: string
  designGroup: string
  variant: number | null
  totalVariants: number
  src: string
}

export const PIXEL_SPRITE_CATALOG: PixelSpriteEntry[] = [
  {
    id: 'male-01-1',
    category: 'male',
    label: 'Male 01',
    designGroup: 'male-01',
    variant: 1,
    totalVariants: 4,
    src: './Male/Male 01-1.png'
  },
  {
    id: 'male-01-2',
    category: 'male',
    label: 'Male 01',
    designGroup: 'male-01',
    variant: 2,
    totalVariants: 4,
    src: './Male/Male 01-2.png'
  },
  {
    id: 'male-01-3',
    category: 'male',
    label: 'Male 01',
    designGroup: 'male-01',
    variant: 3,
    totalVariants: 4,
    src: './Male/Male 01-3.png'
  },
  {
    id: 'male-01-4',
    category: 'male',
    label: 'Male 01',
    designGroup: 'male-01',
    variant: 4,
    totalVariants: 4,
    src: './Male/Male 01-4.png'
  },
  {
    id: 'male-02-1',
    category: 'male',
    label: 'Male 02',
    designGroup: 'male-02',
    variant: 1,
    totalVariants: 4,
    src: './Male/Male 02-1.png'
  },
  {
    id: 'male-02-2',
    category: 'male',
    label: 'Male 02',
    designGroup: 'male-02',
    variant: 2,
    totalVariants: 4,
    src: './Male/Male 02-2.png'
  },
  {
    id: 'male-02-3',
    category: 'male',
    label: 'Male 02',
    designGroup: 'male-02',
    variant: 3,
    totalVariants: 4,
    src: './Male/Male 02-3.png'
  },
  {
    id: 'male-02-4',
    category: 'male',
    label: 'Male 02',
    designGroup: 'male-02',
    variant: 4,
    totalVariants: 4,
    src: './Male/Male 02-4.png'
  },
  {
    id: 'male-03-1',
    category: 'male',
    label: 'Male 03',
    designGroup: 'male-03',
    variant: 1,
    totalVariants: 4,
    src: './Male/Male 03-1.png'
  },
  {
    id: 'male-03-2',
    category: 'male',
    label: 'Male 03',
    designGroup: 'male-03',
    variant: 2,
    totalVariants: 4,
    src: './Male/Male 03-2.png'
  },
  {
    id: 'male-03-3',
    category: 'male',
    label: 'Male 03',
    designGroup: 'male-03',
    variant: 3,
    totalVariants: 4,
    src: './Male/Male 03-3.png'
  },
  {
    id: 'male-03-4',
    category: 'male',
    label: 'Male 03',
    designGroup: 'male-03',
    variant: 4,
    totalVariants: 4,
    src: './Male/Male 03-4.png'
  },
  {
    id: 'male-04-1',
    category: 'male',
    label: 'Male 04',
    designGroup: 'male-04',
    variant: 1,
    totalVariants: 4,
    src: './Male/Male 04-1.png'
  },
  {
    id: 'male-04-2',
    category: 'male',
    label: 'Male 04',
    designGroup: 'male-04',
    variant: 2,
    totalVariants: 4,
    src: './Male/Male 04-2.png'
  },
  {
    id: 'male-04-3',
    category: 'male',
    label: 'Male 04',
    designGroup: 'male-04',
    variant: 3,
    totalVariants: 4,
    src: './Male/Male 04-3.png'
  },
  {
    id: 'male-04-4',
    category: 'male',
    label: 'Male 04',
    designGroup: 'male-04',
    variant: 4,
    totalVariants: 4,
    src: './Male/Male 04-4.png'
  },
  {
    id: 'male-05-1',
    category: 'male',
    label: 'Male 05',
    designGroup: 'male-05',
    variant: 1,
    totalVariants: 4,
    src: './Male/Male 05-1.png'
  },
  {
    id: 'male-05-2',
    category: 'male',
    label: 'Male 05',
    designGroup: 'male-05',
    variant: 2,
    totalVariants: 4,
    src: './Male/Male 05-2.png'
  },
  {
    id: 'male-05-3',
    category: 'male',
    label: 'Male 05',
    designGroup: 'male-05',
    variant: 3,
    totalVariants: 4,
    src: './Male/Male 05-3.png'
  },
  {
    id: 'male-05-4',
    category: 'male',
    label: 'Male 05',
    designGroup: 'male-05',
    variant: 4,
    totalVariants: 4,
    src: './Male/Male 05-4.png'
  },
  {
    id: 'male-06-1',
    category: 'male',
    label: 'Male 06',
    designGroup: 'male-06',
    variant: 1,
    totalVariants: 4,
    src: './Male/Male 06-1.png'
  },
  {
    id: 'male-06-2',
    category: 'male',
    label: 'Male 06',
    designGroup: 'male-06',
    variant: 2,
    totalVariants: 4,
    src: './Male/Male 06-2.png'
  },
  {
    id: 'male-06-3',
    category: 'male',
    label: 'Male 06',
    designGroup: 'male-06',
    variant: 3,
    totalVariants: 4,
    src: './Male/Male 06-3.png'
  },
  {
    id: 'male-06-4',
    category: 'male',
    label: 'Male 06',
    designGroup: 'male-06',
    variant: 4,
    totalVariants: 4,
    src: './Male/Male 06-4.png'
  },
  {
    id: 'male-07-1',
    category: 'male',
    label: 'Male 07',
    designGroup: 'male-07',
    variant: 1,
    totalVariants: 4,
    src: './Male/Male 07-1.png'
  },
  {
    id: 'male-07-2',
    category: 'male',
    label: 'Male 07',
    designGroup: 'male-07',
    variant: 2,
    totalVariants: 4,
    src: './Male/Male 07-2.png'
  },
  {
    id: 'male-07-3',
    category: 'male',
    label: 'Male 07',
    designGroup: 'male-07',
    variant: 3,
    totalVariants: 4,
    src: './Male/Male 07-3.png'
  },
  {
    id: 'male-07-4',
    category: 'male',
    label: 'Male 07',
    designGroup: 'male-07',
    variant: 4,
    totalVariants: 4,
    src: './Male/Male 07-4.png'
  },
  {
    id: 'male-08-1',
    category: 'male',
    label: 'Male 08',
    designGroup: 'male-08',
    variant: 1,
    totalVariants: 4,
    src: './Male/Male 08-1.png'
  },
  {
    id: 'male-08-2',
    category: 'male',
    label: 'Male 08',
    designGroup: 'male-08',
    variant: 2,
    totalVariants: 4,
    src: './Male/Male 08-2.png'
  },
  {
    id: 'male-08-3',
    category: 'male',
    label: 'Male 08',
    designGroup: 'male-08',
    variant: 3,
    totalVariants: 4,
    src: './Male/Male 08-3.png'
  },
  {
    id: 'male-08-4',
    category: 'male',
    label: 'Male 08',
    designGroup: 'male-08',
    variant: 4,
    totalVariants: 4,
    src: './Male/Male 08-4.png'
  },
  {
    id: 'male-09-1',
    category: 'male',
    label: 'Male 09',
    designGroup: 'male-09',
    variant: 1,
    totalVariants: 4,
    src: './Male/Male 09-1.png'
  },
  {
    id: 'male-09-2',
    category: 'male',
    label: 'Male 09',
    designGroup: 'male-09',
    variant: 2,
    totalVariants: 4,
    src: './Male/Male 09-2.png'
  },
  {
    id: 'male-09-3',
    category: 'male',
    label: 'Male 09',
    designGroup: 'male-09',
    variant: 3,
    totalVariants: 4,
    src: './Male/Male 09-3.png'
  },
  {
    id: 'male-09-4',
    category: 'male',
    label: 'Male 09',
    designGroup: 'male-09',
    variant: 4,
    totalVariants: 4,
    src: './Male/Male 09-4.png'
  },
  {
    id: 'male-10-1',
    category: 'male',
    label: 'Male 10',
    designGroup: 'male-10',
    variant: 1,
    totalVariants: 4,
    src: './Male/Male 10-1.png'
  },
  {
    id: 'male-10-2',
    category: 'male',
    label: 'Male 10',
    designGroup: 'male-10',
    variant: 2,
    totalVariants: 4,
    src: './Male/Male 10-2.png'
  },
  {
    id: 'male-10-3',
    category: 'male',
    label: 'Male 10',
    designGroup: 'male-10',
    variant: 3,
    totalVariants: 4,
    src: './Male/Male 10-3.png'
  },
  {
    id: 'male-10-4',
    category: 'male',
    label: 'Male 10',
    designGroup: 'male-10',
    variant: 4,
    totalVariants: 4,
    src: './Male/Male 10-4.png'
  },
  {
    id: 'male-11-1',
    category: 'male',
    label: 'Male 11',
    designGroup: 'male-11',
    variant: 1,
    totalVariants: 4,
    src: './Male/Male 11-1.png'
  },
  {
    id: 'male-11-2',
    category: 'male',
    label: 'Male 11',
    designGroup: 'male-11',
    variant: 2,
    totalVariants: 4,
    src: './Male/Male 11-2.png'
  },
  {
    id: 'male-11-3',
    category: 'male',
    label: 'Male 11',
    designGroup: 'male-11',
    variant: 3,
    totalVariants: 4,
    src: './Male/Male 11-3.png'
  },
  {
    id: 'male-11-4',
    category: 'male',
    label: 'Male 11',
    designGroup: 'male-11',
    variant: 4,
    totalVariants: 4,
    src: './Male/Male 11-4.png'
  },
  {
    id: 'male-12-1',
    category: 'male',
    label: 'Male 12',
    designGroup: 'male-12',
    variant: 1,
    totalVariants: 4,
    src: './Male/Male 12-1.png'
  },
  {
    id: 'male-12-2',
    category: 'male',
    label: 'Male 12',
    designGroup: 'male-12',
    variant: 2,
    totalVariants: 4,
    src: './Male/Male 12-2.png'
  },
  {
    id: 'male-12-3',
    category: 'male',
    label: 'Male 12',
    designGroup: 'male-12',
    variant: 3,
    totalVariants: 4,
    src: './Male/Male 12-3.png'
  },
  {
    id: 'male-12-4',
    category: 'male',
    label: 'Male 12',
    designGroup: 'male-12',
    variant: 4,
    totalVariants: 4,
    src: './Male/Male 12-4.png'
  },
  {
    id: 'male-13-1',
    category: 'male',
    label: 'Male 13',
    designGroup: 'male-13',
    variant: 1,
    totalVariants: 4,
    src: './Male/Male 13-1.png'
  },
  {
    id: 'male-13-2',
    category: 'male',
    label: 'Male 13',
    designGroup: 'male-13',
    variant: 2,
    totalVariants: 4,
    src: './Male/Male 13-2.png'
  },
  {
    id: 'male-13-3',
    category: 'male',
    label: 'Male 13',
    designGroup: 'male-13',
    variant: 3,
    totalVariants: 4,
    src: './Male/Male 13-3.png'
  },
  {
    id: 'male-13-4',
    category: 'male',
    label: 'Male 13',
    designGroup: 'male-13',
    variant: 4,
    totalVariants: 4,
    src: './Male/Male 13-4.png'
  },
  {
    id: 'male-14-1',
    category: 'male',
    label: 'Male 14',
    designGroup: 'male-14',
    variant: 1,
    totalVariants: 4,
    src: './Male/Male 14-1.png'
  },
  {
    id: 'male-14-2',
    category: 'male',
    label: 'Male 14',
    designGroup: 'male-14',
    variant: 2,
    totalVariants: 4,
    src: './Male/Male 14-2.png'
  },
  {
    id: 'male-14-3',
    category: 'male',
    label: 'Male 14',
    designGroup: 'male-14',
    variant: 3,
    totalVariants: 4,
    src: './Male/Male 14-3.png'
  },
  {
    id: 'male-14-4',
    category: 'male',
    label: 'Male 14',
    designGroup: 'male-14',
    variant: 4,
    totalVariants: 4,
    src: './Male/Male 14-4.png'
  },
  {
    id: 'male-15-1',
    category: 'male',
    label: 'Male 15',
    designGroup: 'male-15',
    variant: 1,
    totalVariants: 4,
    src: './Male/Male 15-1.png'
  },
  {
    id: 'male-15-2',
    category: 'male',
    label: 'Male 15',
    designGroup: 'male-15',
    variant: 2,
    totalVariants: 4,
    src: './Male/Male 15-2.png'
  },
  {
    id: 'male-15-3',
    category: 'male',
    label: 'Male 15',
    designGroup: 'male-15',
    variant: 3,
    totalVariants: 4,
    src: './Male/Male 15-3.png'
  },
  {
    id: 'male-15-4',
    category: 'male',
    label: 'Male 15',
    designGroup: 'male-15',
    variant: 4,
    totalVariants: 4,
    src: './Male/Male 15-4.png'
  },
  {
    id: 'male-16-1',
    category: 'male',
    label: 'Male 16',
    designGroup: 'male-16',
    variant: 1,
    totalVariants: 4,
    src: './Male/Male 16-1.png'
  },
  {
    id: 'male-16-2',
    category: 'male',
    label: 'Male 16',
    designGroup: 'male-16',
    variant: 2,
    totalVariants: 4,
    src: './Male/Male 16-2.png'
  },
  {
    id: 'male-16-3',
    category: 'male',
    label: 'Male 16',
    designGroup: 'male-16',
    variant: 3,
    totalVariants: 4,
    src: './Male/Male 16-3.png'
  },
  {
    id: 'male-16-4',
    category: 'male',
    label: 'Male 16',
    designGroup: 'male-16',
    variant: 4,
    totalVariants: 4,
    src: './Male/Male 16-4.png'
  },
  {
    id: 'male-17-1',
    category: 'male',
    label: 'Male 17',
    designGroup: 'male-17',
    variant: 1,
    totalVariants: 4,
    src: './Male/Male 17-1.png'
  },
  {
    id: 'male-17-2',
    category: 'male',
    label: 'Male 17',
    designGroup: 'male-17',
    variant: 2,
    totalVariants: 4,
    src: './Male/Male 17-2.png'
  },
  {
    id: 'male-17-3',
    category: 'male',
    label: 'Male 17',
    designGroup: 'male-17',
    variant: 3,
    totalVariants: 4,
    src: './Male/Male 17-3.png'
  },
  {
    id: 'male-17-4',
    category: 'male',
    label: 'Male 17',
    designGroup: 'male-17',
    variant: 4,
    totalVariants: 4,
    src: './Male/Male 17-4.png'
  },
  {
    id: 'male-18-1',
    category: 'male',
    label: 'Male 18',
    designGroup: 'male-18',
    variant: 1,
    totalVariants: 1,
    src: './Male/Male 18-1.png'
  },
  {
    id: 'female-01-1',
    category: 'female',
    label: 'Female 01',
    designGroup: 'female-01',
    variant: 1,
    totalVariants: 4,
    src: './Female/Female 01-1.png'
  },
  {
    id: 'female-01-2',
    category: 'female',
    label: 'Female 01',
    designGroup: 'female-01',
    variant: 2,
    totalVariants: 4,
    src: './Female/Female 01-2.png'
  },
  {
    id: 'female-01-3',
    category: 'female',
    label: 'Female 01',
    designGroup: 'female-01',
    variant: 3,
    totalVariants: 4,
    src: './Female/Female 01-3.png'
  },
  {
    id: 'female-01-4',
    category: 'female',
    label: 'Female 01',
    designGroup: 'female-01',
    variant: 4,
    totalVariants: 4,
    src: './Female/Female 01-4.png'
  },
  {
    id: 'female-02-1',
    category: 'female',
    label: 'Female 02',
    designGroup: 'female-02',
    variant: 1,
    totalVariants: 4,
    src: './Female/Female 02-1.png'
  },
  {
    id: 'female-02-2',
    category: 'female',
    label: 'Female 02',
    designGroup: 'female-02',
    variant: 2,
    totalVariants: 4,
    src: './Female/Female 02-2.png'
  },
  {
    id: 'female-02-3',
    category: 'female',
    label: 'Female 02',
    designGroup: 'female-02',
    variant: 3,
    totalVariants: 4,
    src: './Female/Female 02-3.png'
  },
  {
    id: 'female-02-4',
    category: 'female',
    label: 'Female 02',
    designGroup: 'female-02',
    variant: 4,
    totalVariants: 4,
    src: './Female/Female 02-4.png'
  },
  {
    id: 'female-03-1',
    category: 'female',
    label: 'Female 03',
    designGroup: 'female-03',
    variant: 1,
    totalVariants: 4,
    src: './Female/Female 03-1.png'
  },
  {
    id: 'female-03-2',
    category: 'female',
    label: 'Female 03',
    designGroup: 'female-03',
    variant: 2,
    totalVariants: 4,
    src: './Female/Female 03-2.png'
  },
  {
    id: 'female-03-3',
    category: 'female',
    label: 'Female 03',
    designGroup: 'female-03',
    variant: 3,
    totalVariants: 4,
    src: './Female/Female 03-3.png'
  },
  {
    id: 'female-03-4',
    category: 'female',
    label: 'Female 03',
    designGroup: 'female-03',
    variant: 4,
    totalVariants: 4,
    src: './Female/Female 03-4.png'
  },
  {
    id: 'female-04-1',
    category: 'female',
    label: 'Female 04',
    designGroup: 'female-04',
    variant: 1,
    totalVariants: 4,
    src: './Female/Female 04-1.png'
  },
  {
    id: 'female-04-2',
    category: 'female',
    label: 'Female 04',
    designGroup: 'female-04',
    variant: 2,
    totalVariants: 4,
    src: './Female/Female 04-2.png'
  },
  {
    id: 'female-04-3',
    category: 'female',
    label: 'Female 04',
    designGroup: 'female-04',
    variant: 3,
    totalVariants: 4,
    src: './Female/Female 04-3.png'
  },
  {
    id: 'female-04-4',
    category: 'female',
    label: 'Female 04',
    designGroup: 'female-04',
    variant: 4,
    totalVariants: 4,
    src: './Female/Female 04-4.png'
  },
  {
    id: 'female-05-1',
    category: 'female',
    label: 'Female 05',
    designGroup: 'female-05',
    variant: 1,
    totalVariants: 4,
    src: './Female/Female 05-1.png'
  },
  {
    id: 'female-05-2',
    category: 'female',
    label: 'Female 05',
    designGroup: 'female-05',
    variant: 2,
    totalVariants: 4,
    src: './Female/Female 05-2.png'
  },
  {
    id: 'female-05-3',
    category: 'female',
    label: 'Female 05',
    designGroup: 'female-05',
    variant: 3,
    totalVariants: 4,
    src: './Female/Female 05-3.png'
  },
  {
    id: 'female-05-4',
    category: 'female',
    label: 'Female 05',
    designGroup: 'female-05',
    variant: 4,
    totalVariants: 4,
    src: './Female/Female 05-4.png'
  },
  {
    id: 'female-06-1',
    category: 'female',
    label: 'Female 06',
    designGroup: 'female-06',
    variant: 1,
    totalVariants: 4,
    src: './Female/Female 06-1.png'
  },
  {
    id: 'female-06-2',
    category: 'female',
    label: 'Female 06',
    designGroup: 'female-06',
    variant: 2,
    totalVariants: 4,
    src: './Female/Female 06-2.png'
  },
  {
    id: 'female-06-3',
    category: 'female',
    label: 'Female 06',
    designGroup: 'female-06',
    variant: 3,
    totalVariants: 4,
    src: './Female/Female 06-3.png'
  },
  {
    id: 'female-06-4',
    category: 'female',
    label: 'Female 06',
    designGroup: 'female-06',
    variant: 4,
    totalVariants: 4,
    src: './Female/Female 06-4.png'
  },
  {
    id: 'female-07-1',
    category: 'female',
    label: 'Female 07',
    designGroup: 'female-07',
    variant: 1,
    totalVariants: 4,
    src: './Female/Female 07-1.png'
  },
  {
    id: 'female-07-2',
    category: 'female',
    label: 'Female 07',
    designGroup: 'female-07',
    variant: 2,
    totalVariants: 4,
    src: './Female/Female 07-2.png'
  },
  {
    id: 'female-07-3',
    category: 'female',
    label: 'Female 07',
    designGroup: 'female-07',
    variant: 3,
    totalVariants: 4,
    src: './Female/Female 07-3.png'
  },
  {
    id: 'female-07-4',
    category: 'female',
    label: 'Female 07',
    designGroup: 'female-07',
    variant: 4,
    totalVariants: 4,
    src: './Female/Female 07-4.png'
  },
  {
    id: 'female-08-1',
    category: 'female',
    label: 'Female 08',
    designGroup: 'female-08',
    variant: 1,
    totalVariants: 4,
    src: './Female/Female 08-1.png'
  },
  {
    id: 'female-08-2',
    category: 'female',
    label: 'Female 08',
    designGroup: 'female-08',
    variant: 2,
    totalVariants: 4,
    src: './Female/Female 08-2.png'
  },
  {
    id: 'female-08-3',
    category: 'female',
    label: 'Female 08',
    designGroup: 'female-08',
    variant: 3,
    totalVariants: 4,
    src: './Female/Female 08-3.png'
  },
  {
    id: 'female-08-4',
    category: 'female',
    label: 'Female 08',
    designGroup: 'female-08',
    variant: 4,
    totalVariants: 4,
    src: './Female/Female 08-4.png'
  },
  {
    id: 'female-09-1',
    category: 'female',
    label: 'Female 09',
    designGroup: 'female-09',
    variant: 1,
    totalVariants: 4,
    src: './Female/Female 09-1.png'
  },
  {
    id: 'female-09-2',
    category: 'female',
    label: 'Female 09',
    designGroup: 'female-09',
    variant: 2,
    totalVariants: 4,
    src: './Female/Female 09-2.png'
  },
  {
    id: 'female-09-3',
    category: 'female',
    label: 'Female 09',
    designGroup: 'female-09',
    variant: 3,
    totalVariants: 4,
    src: './Female/Female 09-3.png'
  },
  {
    id: 'female-09-4',
    category: 'female',
    label: 'Female 09',
    designGroup: 'female-09',
    variant: 4,
    totalVariants: 4,
    src: './Female/Female 09-4.png'
  },
  {
    id: 'female-10-1',
    category: 'female',
    label: 'Female 10',
    designGroup: 'female-10',
    variant: 1,
    totalVariants: 4,
    src: './Female/Female 10-1.png'
  },
  {
    id: 'female-10-2',
    category: 'female',
    label: 'Female 10',
    designGroup: 'female-10',
    variant: 2,
    totalVariants: 4,
    src: './Female/Female 10-2.png'
  },
  {
    id: 'female-10-3',
    category: 'female',
    label: 'Female 10',
    designGroup: 'female-10',
    variant: 3,
    totalVariants: 4,
    src: './Female/Female 10-3.png'
  },
  {
    id: 'female-10-4',
    category: 'female',
    label: 'Female 10',
    designGroup: 'female-10',
    variant: 4,
    totalVariants: 4,
    src: './Female/Female 10-4.png'
  },
  {
    id: 'female-11-1',
    category: 'female',
    label: 'Female 11',
    designGroup: 'female-11',
    variant: 1,
    totalVariants: 4,
    src: './Female/Female 11-1.png'
  },
  {
    id: 'female-11-2',
    category: 'female',
    label: 'Female 11',
    designGroup: 'female-11',
    variant: 2,
    totalVariants: 4,
    src: './Female/Female 11-2.png'
  },
  {
    id: 'female-11-3',
    category: 'female',
    label: 'Female 11',
    designGroup: 'female-11',
    variant: 3,
    totalVariants: 4,
    src: './Female/Female 11-3.png'
  },
  {
    id: 'female-11-4',
    category: 'female',
    label: 'Female 11',
    designGroup: 'female-11',
    variant: 4,
    totalVariants: 4,
    src: './Female/Female 11-4.png'
  },
  {
    id: 'female-12-1',
    category: 'female',
    label: 'Female 12',
    designGroup: 'female-12',
    variant: 1,
    totalVariants: 4,
    src: './Female/Female 12-1.png'
  },
  {
    id: 'female-12-2',
    category: 'female',
    label: 'Female 12',
    designGroup: 'female-12',
    variant: 2,
    totalVariants: 4,
    src: './Female/Female 12-2.png'
  },
  {
    id: 'female-12-3',
    category: 'female',
    label: 'Female 12',
    designGroup: 'female-12',
    variant: 3,
    totalVariants: 4,
    src: './Female/Female 12-3.png'
  },
  {
    id: 'female-12-4',
    category: 'female',
    label: 'Female 12',
    designGroup: 'female-12',
    variant: 4,
    totalVariants: 4,
    src: './Female/Female 12-4.png'
  },
  {
    id: 'female-13-1',
    category: 'female',
    label: 'Female 13',
    designGroup: 'female-13',
    variant: 1,
    totalVariants: 4,
    src: './Female/Female 13-1.png'
  },
  {
    id: 'female-13-2',
    category: 'female',
    label: 'Female 13',
    designGroup: 'female-13',
    variant: 2,
    totalVariants: 4,
    src: './Female/Female 13-2.png'
  },
  {
    id: 'female-13-3',
    category: 'female',
    label: 'Female 13',
    designGroup: 'female-13',
    variant: 3,
    totalVariants: 4,
    src: './Female/Female 13-3.png'
  },
  {
    id: 'female-13-4',
    category: 'female',
    label: 'Female 13',
    designGroup: 'female-13',
    variant: 4,
    totalVariants: 4,
    src: './Female/Female 13-4.png'
  },
  {
    id: 'female-14-1',
    category: 'female',
    label: 'Female 14',
    designGroup: 'female-14',
    variant: 1,
    totalVariants: 4,
    src: './Female/Female 14-1.png'
  },
  {
    id: 'female-14-2',
    category: 'female',
    label: 'Female 14',
    designGroup: 'female-14',
    variant: 2,
    totalVariants: 4,
    src: './Female/Female 14-2.png'
  },
  {
    id: 'female-14-3',
    category: 'female',
    label: 'Female 14',
    designGroup: 'female-14',
    variant: 3,
    totalVariants: 4,
    src: './Female/Female 14-3.png'
  },
  {
    id: 'female-14-4',
    category: 'female',
    label: 'Female 14',
    designGroup: 'female-14',
    variant: 4,
    totalVariants: 4,
    src: './Female/Female 14-4.png'
  },
  {
    id: 'female-15-1',
    category: 'female',
    label: 'Female 15',
    designGroup: 'female-15',
    variant: 1,
    totalVariants: 4,
    src: './Female/Female 15-1.png'
  },
  {
    id: 'female-15-2',
    category: 'female',
    label: 'Female 15',
    designGroup: 'female-15',
    variant: 2,
    totalVariants: 4,
    src: './Female/Female 15-2.png'
  },
  {
    id: 'female-15-3',
    category: 'female',
    label: 'Female 15',
    designGroup: 'female-15',
    variant: 3,
    totalVariants: 4,
    src: './Female/Female 15-3.png'
  },
  {
    id: 'female-15-4',
    category: 'female',
    label: 'Female 15',
    designGroup: 'female-15',
    variant: 4,
    totalVariants: 4,
    src: './Female/Female 15-4.png'
  },
  {
    id: 'female-16-1',
    category: 'female',
    label: 'Female 16',
    designGroup: 'female-16',
    variant: 1,
    totalVariants: 4,
    src: './Female/Female 16-1.png'
  },
  {
    id: 'female-16-2',
    category: 'female',
    label: 'Female 16',
    designGroup: 'female-16',
    variant: 2,
    totalVariants: 4,
    src: './Female/Female 16-2.png'
  },
  {
    id: 'female-16-3',
    category: 'female',
    label: 'Female 16',
    designGroup: 'female-16',
    variant: 3,
    totalVariants: 4,
    src: './Female/Female 16-3.png'
  },
  {
    id: 'female-16-4',
    category: 'female',
    label: 'Female 16',
    designGroup: 'female-16',
    variant: 4,
    totalVariants: 4,
    src: './Female/Female 16-4.png'
  },
  {
    id: 'female-17-1',
    category: 'female',
    label: 'Female 17',
    designGroup: 'female-17',
    variant: 1,
    totalVariants: 4,
    src: './Female/Female 17-1.png'
  },
  {
    id: 'female-17-2',
    category: 'female',
    label: 'Female 17',
    designGroup: 'female-17',
    variant: 2,
    totalVariants: 4,
    src: './Female/Female 17-2.png'
  },
  {
    id: 'female-17-3',
    category: 'female',
    label: 'Female 17',
    designGroup: 'female-17',
    variant: 3,
    totalVariants: 4,
    src: './Female/Female 17-3.png'
  },
  {
    id: 'female-17-4',
    category: 'female',
    label: 'Female 17',
    designGroup: 'female-17',
    variant: 4,
    totalVariants: 4,
    src: './Female/Female 17-4.png'
  },
  {
    id: 'female-18-1',
    category: 'female',
    label: 'Female 18',
    designGroup: 'female-18',
    variant: 1,
    totalVariants: 4,
    src: './Female/Female 18-1.png'
  },
  {
    id: 'female-18-2',
    category: 'female',
    label: 'Female 18',
    designGroup: 'female-18',
    variant: 2,
    totalVariants: 4,
    src: './Female/Female 18-2.png'
  },
  {
    id: 'female-18-3',
    category: 'female',
    label: 'Female 18',
    designGroup: 'female-18',
    variant: 3,
    totalVariants: 4,
    src: './Female/Female 18-3.png'
  },
  {
    id: 'female-18-4',
    category: 'female',
    label: 'Female 18',
    designGroup: 'female-18',
    variant: 4,
    totalVariants: 4,
    src: './Female/Female 18-4.png'
  },
  {
    id: 'female-19-1',
    category: 'female',
    label: 'Female 19',
    designGroup: 'female-19',
    variant: 1,
    totalVariants: 4,
    src: './Female/Female 19-1.png'
  },
  {
    id: 'female-19-2',
    category: 'female',
    label: 'Female 19',
    designGroup: 'female-19',
    variant: 2,
    totalVariants: 4,
    src: './Female/Female 19-2.png'
  },
  {
    id: 'female-19-3',
    category: 'female',
    label: 'Female 19',
    designGroup: 'female-19',
    variant: 3,
    totalVariants: 4,
    src: './Female/Female 19-3.png'
  },
  {
    id: 'female-19-4',
    category: 'female',
    label: 'Female 19',
    designGroup: 'female-19',
    variant: 4,
    totalVariants: 4,
    src: './Female/Female 19-4.png'
  },
  {
    id: 'female-20-1',
    category: 'female',
    label: 'Female 20',
    designGroup: 'female-20',
    variant: 1,
    totalVariants: 4,
    src: './Female/Female 20-1.png'
  },
  {
    id: 'female-20-2',
    category: 'female',
    label: 'Female 20',
    designGroup: 'female-20',
    variant: 2,
    totalVariants: 4,
    src: './Female/Female 20-2.png'
  },
  {
    id: 'female-20-3',
    category: 'female',
    label: 'Female 20',
    designGroup: 'female-20',
    variant: 3,
    totalVariants: 4,
    src: './Female/Female 20-3.png'
  },
  {
    id: 'female-20-4',
    category: 'female',
    label: 'Female 20',
    designGroup: 'female-20',
    variant: 4,
    totalVariants: 4,
    src: './Female/Female 20-4.png'
  },
  {
    id: 'female-21-1',
    category: 'female',
    label: 'Female 21',
    designGroup: 'female-21',
    variant: 1,
    totalVariants: 4,
    src: './Female/Female 21-1.png'
  },
  {
    id: 'female-21-2',
    category: 'female',
    label: 'Female 21',
    designGroup: 'female-21',
    variant: 2,
    totalVariants: 4,
    src: './Female/Female 21-2.png'
  },
  {
    id: 'female-21-3',
    category: 'female',
    label: 'Female 21',
    designGroup: 'female-21',
    variant: 3,
    totalVariants: 4,
    src: './Female/Female 21-3.png'
  },
  {
    id: 'female-21-4',
    category: 'female',
    label: 'Female 21',
    designGroup: 'female-21',
    variant: 4,
    totalVariants: 4,
    src: './Female/Female 21-4.png'
  },
  {
    id: 'female-22-1',
    category: 'female',
    label: 'Female 22',
    designGroup: 'female-22',
    variant: 1,
    totalVariants: 4,
    src: './Female/Female 22-1.png'
  },
  {
    id: 'female-22-2',
    category: 'female',
    label: 'Female 22',
    designGroup: 'female-22',
    variant: 2,
    totalVariants: 4,
    src: './Female/Female 22-2.png'
  },
  {
    id: 'female-22-3',
    category: 'female',
    label: 'Female 22',
    designGroup: 'female-22',
    variant: 3,
    totalVariants: 4,
    src: './Female/Female 22-3.png'
  },
  {
    id: 'female-22-4',
    category: 'female',
    label: 'Female 22',
    designGroup: 'female-22',
    variant: 4,
    totalVariants: 4,
    src: './Female/Female 22-4.png'
  },
  {
    id: 'female-23-1',
    category: 'female',
    label: 'Female 23',
    designGroup: 'female-23',
    variant: 1,
    totalVariants: 1,
    src: './Female/Female 23-1.png'
  },
  {
    id: 'female-24-1',
    category: 'female',
    label: 'Female 24',
    designGroup: 'female-24',
    variant: 1,
    totalVariants: 1,
    src: './Female/Female 24-1.png'
  },
  {
    id: 'female-25-1',
    category: 'female',
    label: 'Female 25',
    designGroup: 'female-25',
    variant: 1,
    totalVariants: 1,
    src: './Female/Female 25-1.png'
  },
  {
    id: 'soldier-01-1',
    category: 'soldier',
    label: 'Soldier 01',
    designGroup: 'soldier-01',
    variant: 1,
    totalVariants: 4,
    src: './Soldier/Soldier 01-1.png'
  },
  {
    id: 'soldier-01-2',
    category: 'soldier',
    label: 'Soldier 01',
    designGroup: 'soldier-01',
    variant: 2,
    totalVariants: 4,
    src: './Soldier/Soldier 01-2.png'
  },
  {
    id: 'soldier-01-3',
    category: 'soldier',
    label: 'Soldier 01',
    designGroup: 'soldier-01',
    variant: 3,
    totalVariants: 4,
    src: './Soldier/Soldier 01-3.png'
  },
  {
    id: 'soldier-01-4',
    category: 'soldier',
    label: 'Soldier 01',
    designGroup: 'soldier-01',
    variant: 4,
    totalVariants: 4,
    src: './Soldier/Soldier 01-4.png'
  },
  {
    id: 'soldier-02-1',
    category: 'soldier',
    label: 'Soldier 02',
    designGroup: 'soldier-02',
    variant: 1,
    totalVariants: 4,
    src: './Soldier/Soldier 02-1.png'
  },
  {
    id: 'soldier-02-2',
    category: 'soldier',
    label: 'Soldier 02',
    designGroup: 'soldier-02',
    variant: 2,
    totalVariants: 4,
    src: './Soldier/Soldier 02-2.png'
  },
  {
    id: 'soldier-02-3',
    category: 'soldier',
    label: 'Soldier 02',
    designGroup: 'soldier-02',
    variant: 3,
    totalVariants: 4,
    src: './Soldier/Soldier 02-3.png'
  },
  {
    id: 'soldier-02-4',
    category: 'soldier',
    label: 'Soldier 02',
    designGroup: 'soldier-02',
    variant: 4,
    totalVariants: 4,
    src: './Soldier/Soldier 02-4.png'
  },
  {
    id: 'soldier-03-1',
    category: 'soldier',
    label: 'Soldier 03',
    designGroup: 'soldier-03',
    variant: 1,
    totalVariants: 4,
    src: './Soldier/Soldier 03-1.png'
  },
  {
    id: 'soldier-03-2',
    category: 'soldier',
    label: 'Soldier 03',
    designGroup: 'soldier-03',
    variant: 2,
    totalVariants: 4,
    src: './Soldier/Soldier 03-2.png'
  },
  {
    id: 'soldier-03-3',
    category: 'soldier',
    label: 'Soldier 03',
    designGroup: 'soldier-03',
    variant: 3,
    totalVariants: 4,
    src: './Soldier/Soldier 03-3.png'
  },
  {
    id: 'soldier-03-4',
    category: 'soldier',
    label: 'Soldier 03',
    designGroup: 'soldier-03',
    variant: 4,
    totalVariants: 4,
    src: './Soldier/Soldier 03-4.png'
  },
  {
    id: 'soldier-04-1',
    category: 'soldier',
    label: 'Soldier 04',
    designGroup: 'soldier-04',
    variant: 1,
    totalVariants: 4,
    src: './Soldier/Soldier 04-1.png'
  },
  {
    id: 'soldier-04-2',
    category: 'soldier',
    label: 'Soldier 04',
    designGroup: 'soldier-04',
    variant: 2,
    totalVariants: 4,
    src: './Soldier/Soldier 04-2.png'
  },
  {
    id: 'soldier-04-3',
    category: 'soldier',
    label: 'Soldier 04',
    designGroup: 'soldier-04',
    variant: 3,
    totalVariants: 4,
    src: './Soldier/Soldier 04-3.png'
  },
  {
    id: 'soldier-04-4',
    category: 'soldier',
    label: 'Soldier 04',
    designGroup: 'soldier-04',
    variant: 4,
    totalVariants: 4,
    src: './Soldier/Soldier 04-4.png'
  },
  {
    id: 'soldier-05-1',
    category: 'soldier',
    label: 'Soldier 05',
    designGroup: 'soldier-05',
    variant: 1,
    totalVariants: 4,
    src: './Soldier/Soldier 05-1.png'
  },
  {
    id: 'soldier-05-2',
    category: 'soldier',
    label: 'Soldier 05',
    designGroup: 'soldier-05',
    variant: 2,
    totalVariants: 4,
    src: './Soldier/Soldier 05-2.png'
  },
  {
    id: 'soldier-05-3',
    category: 'soldier',
    label: 'Soldier 05',
    designGroup: 'soldier-05',
    variant: 3,
    totalVariants: 4,
    src: './Soldier/Soldier 05-3.png'
  },
  {
    id: 'soldier-05-4',
    category: 'soldier',
    label: 'Soldier 05',
    designGroup: 'soldier-05',
    variant: 4,
    totalVariants: 4,
    src: './Soldier/Soldier 05-4.png'
  },
  {
    id: 'soldier-06-1',
    category: 'soldier',
    label: 'Soldier 06',
    designGroup: 'soldier-06',
    variant: 1,
    totalVariants: 4,
    src: './Soldier/Soldier 06-1.png'
  },
  {
    id: 'soldier-06-2',
    category: 'soldier',
    label: 'Soldier 06',
    designGroup: 'soldier-06',
    variant: 2,
    totalVariants: 4,
    src: './Soldier/Soldier 06-2.png'
  },
  {
    id: 'soldier-06-3',
    category: 'soldier',
    label: 'Soldier 06',
    designGroup: 'soldier-06',
    variant: 3,
    totalVariants: 4,
    src: './Soldier/Soldier 06-3.png'
  },
  {
    id: 'soldier-06-4',
    category: 'soldier',
    label: 'Soldier 06',
    designGroup: 'soldier-06',
    variant: 4,
    totalVariants: 4,
    src: './Soldier/Soldier 06-4.png'
  },
  {
    id: 'soldier-07-1',
    category: 'soldier',
    label: 'Soldier 07',
    designGroup: 'soldier-07',
    variant: 1,
    totalVariants: 4,
    src: './Soldier/Soldier 07-1.png'
  },
  {
    id: 'soldier-07-2',
    category: 'soldier',
    label: 'Soldier 07',
    designGroup: 'soldier-07',
    variant: 2,
    totalVariants: 4,
    src: './Soldier/Soldier 07-2.png'
  },
  {
    id: 'soldier-07-3',
    category: 'soldier',
    label: 'Soldier 07',
    designGroup: 'soldier-07',
    variant: 3,
    totalVariants: 4,
    src: './Soldier/Soldier 07-3.png'
  },
  {
    id: 'soldier-07-4',
    category: 'soldier',
    label: 'Soldier 07',
    designGroup: 'soldier-07',
    variant: 4,
    totalVariants: 4,
    src: './Soldier/Soldier 07-4.png'
  },
  {
    id: 'enemy-01-1',
    category: 'enemy',
    label: 'Enemy 01',
    designGroup: 'enemy-01',
    variant: 1,
    totalVariants: 1,
    src: './Enemy/Enemy 01-1.png'
  },
  {
    id: 'enemy-02-1',
    category: 'enemy',
    label: 'Enemy 02',
    designGroup: 'enemy-02',
    variant: 1,
    totalVariants: 1,
    src: './Enemy/Enemy 02-1.png'
  },
  {
    id: 'enemy-03-1',
    category: 'enemy',
    label: 'Enemy 03',
    designGroup: 'enemy-03',
    variant: 1,
    totalVariants: 1,
    src: './Enemy/Enemy 03-1.png'
  },
  {
    id: 'enemy-04-1',
    category: 'enemy',
    label: 'Enemy 04',
    designGroup: 'enemy-04',
    variant: 1,
    totalVariants: 1,
    src: './Enemy/Enemy 04-1.png'
  },
  {
    id: 'enemy-05-1',
    category: 'enemy',
    label: 'Enemy 05',
    designGroup: 'enemy-05',
    variant: 1,
    totalVariants: 1,
    src: './Enemy/Enemy 05-1.png'
  },
  {
    id: 'enemy-06-1',
    category: 'enemy',
    label: 'Enemy 06',
    designGroup: 'enemy-06',
    variant: 1,
    totalVariants: 1,
    src: './Enemy/Enemy 06-1.png'
  },
  {
    id: 'enemy-07-1',
    category: 'enemy',
    label: 'Enemy 07',
    designGroup: 'enemy-07',
    variant: 1,
    totalVariants: 1,
    src: './Enemy/Enemy 07-1.png'
  },
  {
    id: 'enemy-08-1',
    category: 'enemy',
    label: 'Enemy 08',
    designGroup: 'enemy-08',
    variant: 1,
    totalVariants: 1,
    src: './Enemy/Enemy 08-1.png'
  },
  {
    id: 'enemy-09-1',
    category: 'enemy',
    label: 'Enemy 09',
    designGroup: 'enemy-09',
    variant: 1,
    totalVariants: 1,
    src: './Enemy/Enemy 09-1.png'
  },
  {
    id: 'enemy-10-1',
    category: 'enemy',
    label: 'Enemy 10',
    designGroup: 'enemy-10',
    variant: 1,
    totalVariants: 1,
    src: './Enemy/Enemy 10-1.png'
  },
  {
    id: 'enemy-11-1',
    category: 'enemy',
    label: 'Enemy 11',
    designGroup: 'enemy-11',
    variant: 1,
    totalVariants: 1,
    src: './Enemy/Enemy 11-1.png'
  },
  {
    id: 'enemy-12-1',
    category: 'enemy',
    label: 'Enemy 12',
    designGroup: 'enemy-12',
    variant: 1,
    totalVariants: 1,
    src: './Enemy/Enemy 12-1.png'
  },
  {
    id: 'enemy-13-1',
    category: 'enemy',
    label: 'Enemy 13',
    designGroup: 'enemy-13',
    variant: 1,
    totalVariants: 1,
    src: './Enemy/Enemy 13-1.png'
  },
  {
    id: 'enemy-14-1',
    category: 'enemy',
    label: 'Enemy 14',
    designGroup: 'enemy-14',
    variant: 1,
    totalVariants: 1,
    src: './Enemy/Enemy 14-1.png'
  },
  {
    id: 'enemy-15-1',
    category: 'enemy',
    label: 'Enemy 15',
    designGroup: 'enemy-15',
    variant: 1,
    totalVariants: 6,
    src: './Enemy/Enemy 15-1.png'
  },
  {
    id: 'enemy-15-2',
    category: 'enemy',
    label: 'Enemy 15',
    designGroup: 'enemy-15',
    variant: 2,
    totalVariants: 6,
    src: './Enemy/Enemy 15-2.png'
  },
  {
    id: 'enemy-15-3',
    category: 'enemy',
    label: 'Enemy 15',
    designGroup: 'enemy-15',
    variant: 3,
    totalVariants: 6,
    src: './Enemy/Enemy 15-3.png'
  },
  {
    id: 'enemy-15-4',
    category: 'enemy',
    label: 'Enemy 15',
    designGroup: 'enemy-15',
    variant: 4,
    totalVariants: 6,
    src: './Enemy/Enemy 15-4.png'
  },
  {
    id: 'enemy-15-5',
    category: 'enemy',
    label: 'Enemy 15',
    designGroup: 'enemy-15',
    variant: 5,
    totalVariants: 6,
    src: './Enemy/Enemy 15-5.png'
  },
  {
    id: 'enemy-15-6',
    category: 'enemy',
    label: 'Enemy 15',
    designGroup: 'enemy-15',
    variant: 6,
    totalVariants: 6,
    src: './Enemy/Enemy 15-6.png'
  },
  {
    id: 'enemy-16-1',
    category: 'enemy',
    label: 'Enemy 16',
    designGroup: 'enemy-16',
    variant: 1,
    totalVariants: 8,
    src: './Enemy/Enemy 16-1.png'
  },
  {
    id: 'enemy-16-2',
    category: 'enemy',
    label: 'Enemy 16',
    designGroup: 'enemy-16',
    variant: 2,
    totalVariants: 8,
    src: './Enemy/Enemy 16-2.png'
  },
  {
    id: 'enemy-16-3',
    category: 'enemy',
    label: 'Enemy 16',
    designGroup: 'enemy-16',
    variant: 3,
    totalVariants: 8,
    src: './Enemy/Enemy 16-3.png'
  },
  {
    id: 'enemy-16-4',
    category: 'enemy',
    label: 'Enemy 16',
    designGroup: 'enemy-16',
    variant: 4,
    totalVariants: 8,
    src: './Enemy/Enemy 16-4.png'
  },
  {
    id: 'enemy-16-5',
    category: 'enemy',
    label: 'Enemy 16',
    designGroup: 'enemy-16',
    variant: 5,
    totalVariants: 8,
    src: './Enemy/Enemy 16-5.png'
  },
  {
    id: 'enemy-16-6',
    category: 'enemy',
    label: 'Enemy 16',
    designGroup: 'enemy-16',
    variant: 6,
    totalVariants: 8,
    src: './Enemy/Enemy 16-6.png'
  },
  {
    id: 'enemy-16-7',
    category: 'enemy',
    label: 'Enemy 16',
    designGroup: 'enemy-16',
    variant: 7,
    totalVariants: 8,
    src: './Enemy/Enemy 16-7.png'
  },
  {
    id: 'enemy-16-8',
    category: 'enemy',
    label: 'Enemy 16',
    designGroup: 'enemy-16',
    variant: 8,
    totalVariants: 8,
    src: './Enemy/Enemy 16-8.png'
  },
  {
    id: 'enemy-17-1',
    category: 'enemy',
    label: 'Enemy 17',
    designGroup: 'enemy-17',
    variant: 1,
    totalVariants: 8,
    src: './Enemy/Enemy 17-1.png'
  },
  {
    id: 'enemy-17-2',
    category: 'enemy',
    label: 'Enemy 17',
    designGroup: 'enemy-17',
    variant: 2,
    totalVariants: 8,
    src: './Enemy/Enemy 17-2.png'
  },
  {
    id: 'enemy-17-3',
    category: 'enemy',
    label: 'Enemy 17',
    designGroup: 'enemy-17',
    variant: 3,
    totalVariants: 8,
    src: './Enemy/Enemy 17-3.png'
  },
  {
    id: 'enemy-17-4',
    category: 'enemy',
    label: 'Enemy 17',
    designGroup: 'enemy-17',
    variant: 4,
    totalVariants: 8,
    src: './Enemy/Enemy 17-4.png'
  },
  {
    id: 'enemy-17-5',
    category: 'enemy',
    label: 'Enemy 17',
    designGroup: 'enemy-17',
    variant: 5,
    totalVariants: 8,
    src: './Enemy/Enemy 17-5.png'
  },
  {
    id: 'enemy-17-6',
    category: 'enemy',
    label: 'Enemy 17',
    designGroup: 'enemy-17',
    variant: 6,
    totalVariants: 8,
    src: './Enemy/Enemy 17-6.png'
  },
  {
    id: 'enemy-17-7',
    category: 'enemy',
    label: 'Enemy 17',
    designGroup: 'enemy-17',
    variant: 7,
    totalVariants: 8,
    src: './Enemy/Enemy 17-7.png'
  },
  {
    id: 'enemy-17-8',
    category: 'enemy',
    label: 'Enemy 17',
    designGroup: 'enemy-17',
    variant: 8,
    totalVariants: 8,
    src: './Enemy/Enemy 17-8.png'
  },
  {
    id: 'enemy-18',
    category: 'enemy',
    label: 'Enemy 18',
    designGroup: 'enemy-18',
    variant: null,
    totalVariants: 1,
    src: './Enemy/Enemy 18.png'
  },
  {
    id: 'enemy-19',
    category: 'enemy',
    label: 'Enemy 19',
    designGroup: 'enemy-19',
    variant: null,
    totalVariants: 1,
    src: './Enemy/Enemy 19.png'
  },
  {
    id: 'enemy-20',
    category: 'enemy',
    label: 'Enemy 20',
    designGroup: 'enemy-20',
    variant: null,
    totalVariants: 1,
    src: './Enemy/Enemy 20.png'
  },
  {
    id: 'enemy-21',
    category: 'enemy',
    label: 'Enemy 21',
    designGroup: 'enemy-21',
    variant: null,
    totalVariants: 1,
    src: './Enemy/Enemy 21.png'
  },
  {
    id: 'enemy-22',
    category: 'enemy',
    label: 'Enemy 22',
    designGroup: 'enemy-22',
    variant: null,
    totalVariants: 1,
    src: './Enemy/Enemy 22.png'
  },
  {
    id: 'other-ironman-01',
    category: 'other',
    label: 'Ironman 01',
    designGroup: 'other-ironman-01',
    variant: null,
    totalVariants: 1,
    src: './Other/ironman-01.png'
  },
  {
    id: 'other-pien',
    category: 'other',
    label: 'Pien',
    designGroup: 'other-pien',
    variant: null,
    totalVariants: 1,
    src: './Other/pien.png'
  },
  {
    id: 'other-pien2',
    category: 'other',
    label: 'Pien2',
    designGroup: 'other-pien2',
    variant: null,
    totalVariants: 1,
    src: './Other/pien2.png'
  },
  {
    id: 'other-pipo-charachip-otaku01',
    category: 'other',
    label: 'Pipo Charachip Otaku01',
    designGroup: 'other-pipo-charachip-otaku01',
    variant: null,
    totalVariants: 1,
    src: './Other/pipo-charachip_otaku01.png'
  },
  {
    id: 'other-pipo-charachip-soldier01',
    category: 'other',
    label: 'Pipo Charachip Soldier01',
    designGroup: 'other-pipo-charachip-soldier01',
    variant: null,
    totalVariants: 1,
    src: './Other/pipo-charachip_soldier01.png'
  },
  {
    id: 'xmas-01',
    category: 'xmas',
    label: 'Xmas 01',
    designGroup: 'xmas-01',
    variant: null,
    totalVariants: 1,
    src: './Xmas/pipo-xmaschara01.png'
  },
  {
    id: 'xmas-02',
    category: 'xmas',
    label: 'Xmas 02',
    designGroup: 'xmas-02',
    variant: null,
    totalVariants: 1,
    src: './Xmas/pipo-xmaschara02.png'
  },
  {
    id: 'xmas-03',
    category: 'xmas',
    label: 'Xmas 03',
    designGroup: 'xmas-03',
    variant: null,
    totalVariants: 1,
    src: './Xmas/pipo-xmaschara03.png'
  },
  {
    id: 'xmas-04',
    category: 'xmas',
    label: 'Xmas 04',
    designGroup: 'xmas-04',
    variant: null,
    totalVariants: 1,
    src: './Xmas/pipo-xmaschara04.png'
  },
  {
    id: 'xmas-05',
    category: 'xmas',
    label: 'Xmas 05',
    designGroup: 'xmas-05',
    variant: null,
    totalVariants: 1,
    src: './Xmas/pipo-xmaschara05.png'
  },
  {
    id: 'xmas-06',
    category: 'xmas',
    label: 'Xmas 06',
    designGroup: 'xmas-06',
    variant: null,
    totalVariants: 1,
    src: './Xmas/pipo-xmaschara06.png'
  }
]

export function getDesignGroups(): string[] {
  return [...new Set(PIXEL_SPRITE_CATALOG.map((entry) => entry.designGroup))]
}

export function getVariants(designGroup: string): PixelSpriteEntry[] {
  return PIXEL_SPRITE_CATALOG.filter((entry) => entry.designGroup === designGroup)
}

export function getSpriteById(id: string): PixelSpriteEntry | undefined {
  return PIXEL_SPRITE_CATALOG.find((entry) => entry.id === id)
}
