/**
 * Unit tests for the preprocessing pipeline pure functions.
 * Tests noise filtering, chunk headers, metadata building, overlap handling, and scope enrichment.
 */
import assert from 'node:assert/strict'
import { test, describe } from './test-harness'
import {
  shouldSkipFile,
  buildChunkHeader,
  buildEmbedText,
  buildMetadata,
  splitLongChunk,
  buildScopeContexts,
  buildScopeHeader,
  extractRelevantImports,
  type RawChunk,
  type ProcessedChunk
} from '../preprocessing.service'

// Helper to create a minimal RawChunk
function makeChunk(overrides: Partial<RawChunk> = {}): RawChunk {
  return {
    id: 'test-chunk-1',
    filePath: 'src/auth/auth.service.ts',
    symbolName: 'validateJwt',
    symbolKind: 'method',
    body: 'validateJwt(token: string): boolean {\n  return jwt.verify(token, this.secret)\n}',
    startLine: 10,
    endLine: 13,
    signature: 'validateJwt(token: string): boolean',
    isPublic: true,
    isAsync: false,
    isStatic: false,
    isAbstract: false,
    language: 'typescript',
    ...overrides
  }
}

// ── shouldSkipFile ──

describe('shouldSkipFile', () => {
  test('skips node_modules paths', () => {
    assert.equal(shouldSkipFile('src/node_modules/foo/index.ts', 'const x = 1'), true)
  })

  test('skips dist paths', () => {
    assert.equal(shouldSkipFile('dist/main/index.js', 'const x = 1'), true)
  })

  test('skips minified files', () => {
    assert.equal(shouldSkipFile('src/bundle.min.js', 'const x = 1'), true)
  })

  test('skips lock files', () => {
    assert.equal(shouldSkipFile('package-lock.json', '{}'), true)
  })

  test('skips auto-generated files by header', () => {
    const content = '// Auto-generated by prisma\nexport interface User { id: string }'
    assert.equal(shouldSkipFile('src/prisma/client.ts', content), true)
  })

  test('skips files with @generated header', () => {
    const content = '/** @generated */\nexport type Foo = string'
    assert.equal(shouldSkipFile('src/gen/foo.ts', content), true)
  })

  test('skips minified content (very long lines)', () => {
    const longLine = 'a'.repeat(600)
    assert.equal(shouldSkipFile('src/app.js', longLine), true)
  })

  test('skips binary-ish content (low alphanumeric ratio)', () => {
    const binary = '\x00\x01\x02\x03\x04\x05'.repeat(100)
    assert.equal(shouldSkipFile('src/data.bin', binary), true)
  })

  test('passes normal source files', () => {
    const content = 'export function hello(): string {\n  return "world"\n}'
    assert.equal(shouldSkipFile('src/hello.ts', content), false)
  })

  test('passes test files', () => {
    const content = 'import assert from "node:assert"\nassert.equal(1, 1)'
    assert.equal(shouldSkipFile('src/__tests__/hello.test.ts', content), false)
  })

  test('applies extra skip patterns', () => {
    const content = 'export const MIGRATION = "v1"'
    assert.equal(shouldSkipFile('src/db/custom-gen/types.ts', content, ['**/custom-gen/**']), true)
  })
})

// ── buildChunkHeader ──

describe('buildChunkHeader', () => {
  test('builds header with all fields', () => {
    const chunk = {
      ...makeChunk(),
      imports: ['jwt', 'ConfigService'],
      className: 'AuthService'
    }
    const header = buildChunkHeader(chunk)

    assert.ok(header.includes('# File: src/auth/auth.service.ts'))
    assert.ok(header.includes('# Language: typescript'))
    assert.ok(header.includes('# Scope: AuthService > validateJwt'))
    assert.ok(header.includes('# Kind: public method'))
    assert.ok(header.includes('# Signature: validateJwt(token: string): boolean'))
    assert.ok(header.includes('# Uses: jwt, ConfigService'))
  })

  test('builds header without class scope', () => {
    const chunk = {
      ...makeChunk({ symbolKind: 'function' }),
      imports: [],
      className: null
    }
    const header = buildChunkHeader(chunk)

    assert.ok(header.includes('# Scope: validateJwt'))
    assert.ok(!header.includes('# Uses:'))
  })

  test('shows private visibility', () => {
    const chunk = {
      ...makeChunk({ isPublic: false }),
      imports: [],
      className: null
    }
    const header = buildChunkHeader(chunk)

    assert.ok(header.includes('# Kind: private method'))
  })

  test('shortens long file paths to last 3 segments', () => {
    const chunk = {
      ...makeChunk({ filePath: 'packages/core/src/deep/nested/file.ts' }),
      imports: [],
      className: null
    }
    const header = buildChunkHeader(chunk)

    assert.ok(header.includes('# File: deep/nested/file.ts'))
  })
})

// ── buildEmbedText ──

describe('buildEmbedText', () => {
  test('combines header and body', () => {
    const chunk = {
      ...makeChunk(),
      imports: ['jwt'],
      className: 'AuthService'
    }
    const text = buildEmbedText(chunk)

    assert.ok(text.includes('# File:'))
    assert.ok(text.includes('validateJwt(token: string)'))
    assert.ok(text.includes('jwt.verify'))
  })
})

// ── buildMetadata ──

describe('buildMetadata', () => {
  test('builds metadata with correct fields', () => {
    const chunk = makeChunk()
    const meta = buildMetadata(chunk, null, 'my-project')

    assert.equal(meta.filePath, 'src/auth/auth.service.ts')
    assert.equal(meta.fileName, 'auth.service.ts')
    assert.equal(meta.projectName, 'my-project')
    assert.equal(meta.symbolName, 'validateJwt')
    assert.equal(meta.symbolKind, 'method')
    assert.equal(meta.language, 'typescript')
    assert.equal(meta.isPublic, true)
    assert.equal(meta.isAsync, false)
    assert.equal(meta.className, null)
    assert.equal(meta.hasDescription, false)
    assert.ok(meta.indexedAt > 0)
  })

  test('includes class name from scope context', () => {
    const chunk = makeChunk()
    const scope = {
      className: 'AuthService',
      classKind: 'class' as const,
      classSignature: 'class AuthService implements IAuth',
      classDecorators: ['@Injectable()'],
      parentClassImports: [],
      siblingMethodSignatures: ['login()', 'logout()']
    }
    const meta = buildMetadata(chunk, scope, 'proj')

    assert.equal(meta.className, 'AuthService')
  })

  test('detects docstring', () => {
    const chunk = makeChunk({ body: '/** JSDoc comment */\nfunction foo() {}' })
    const meta = buildMetadata(chunk, null, 'proj')

    assert.equal(meta.hasDocstring, true)
  })

  test('calculates line count', () => {
    const chunk = makeChunk({ body: 'line1\nline2\nline3' })
    const meta = buildMetadata(chunk, null, 'proj')

    assert.equal(meta.lineCount, 3)
  })
})

// ── splitLongChunk ──

describe('splitLongChunk', () => {
  test('returns single chunk when under maxLines', () => {
    const chunk: ProcessedChunk = {
      id: 'c1',
      embedText: 'header\nline1\nline2',
      body: 'line1\nline2',
      metadata: buildMetadata(makeChunk({ body: 'line1\nline2' }), null, 'proj')
    }
    const result = splitLongChunk(chunk, 80, 5)

    assert.equal(result.length, 1)
    assert.equal(result[0].id, 'c1')
  })

  test('splits chunk exceeding maxLines', () => {
    const lines = Array.from({ length: 20 }, (_, i) => `line ${i}`)
    const body = lines.join('\n')
    const chunk: ProcessedChunk = {
      id: 'c1',
      embedText: body,
      body,
      metadata: buildMetadata(makeChunk({ body, startLine: 1, endLine: 20 }), null, 'proj')
    }
    const result = splitLongChunk(chunk, 8, 2)

    assert.ok(result.length > 1, `Expected > 1 parts, got ${result.length}`)
    assert.equal(result[0].id, 'c1::part0')
    assert.equal(result[1].id, 'c1::part1')
  })

  test('includes overlap lines in non-first parts', () => {
    const lines = Array.from({ length: 20 }, (_, i) => `line ${i}`)
    const body = lines.join('\n')
    const chunk: ProcessedChunk = {
      id: 'c1',
      embedText: body,
      body,
      metadata: buildMetadata(makeChunk({ body, startLine: 1, endLine: 20 }), null, 'proj')
    }
    const result = splitLongChunk(chunk, 8, 3)

    // Second part should start with overlap lines from first part
    const secondPartLines = result[1].body.split('\n')
    // The overlap means it includes lines from the end of the previous chunk
    assert.ok(secondPartLines.length > 0)
  })

  test('updates symbolName with part info', () => {
    const lines = Array.from({ length: 20 }, (_, i) => `line ${i}`)
    const body = lines.join('\n')
    const chunk: ProcessedChunk = {
      id: 'c1',
      embedText: body,
      body,
      metadata: buildMetadata(makeChunk({ body }), null, 'proj')
    }
    const result = splitLongChunk(chunk, 8, 2)

    assert.ok(result[0].metadata.symbolName.includes('part 1'))
    assert.ok(result[1].metadata.symbolName.includes('part 2'))
  })
})

// ── extractRelevantImports ──

describe('extractRelevantImports', () => {
  test('extracts ES imports used in chunk body', () => {
    const fileContent = `import { verify } from 'jsonwebtoken'\nimport { Logger } from './logger'\n`
    const chunk = makeChunk({ body: 'verify(token, secret)' })
    const imports = extractRelevantImports(fileContent, chunk)

    assert.ok(imports.includes('verify'))
    assert.ok(!imports.includes('Logger'))
  })

  test('extracts default imports used in chunk', () => {
    const fileContent = `import jwt from 'jsonwebtoken'\n`
    const chunk = makeChunk({ body: 'jwt.verify(token)' })
    const imports = extractRelevantImports(fileContent, chunk)

    assert.ok(imports.includes('jwt'))
  })

  test('returns empty array when no imports match', () => {
    const fileContent = `import { Foo } from './foo'\n`
    const chunk = makeChunk({ body: 'const x = 1' })
    const imports = extractRelevantImports(fileContent, chunk)

    assert.equal(imports.length, 0)
  })

  test('deduplicates imports', () => {
    const fileContent = `import { verify } from 'jsonwebtoken'\nimport { verify as v } from 'other'\n`
    const chunk = makeChunk({ body: 'verify(token)' })
    const imports = extractRelevantImports(fileContent, chunk)

    // Should contain verify only once
    const verifyCount = imports.filter((i) => i === 'verify').length
    assert.equal(verifyCount, 1)
  })

  test('caps at 8 imports', () => {
    const importLines = Array.from({ length: 15 }, (_, i) => `import { fn${i} } from './m${i}'`)
    const fileContent = importLines.join('\n')
    const bodyParts = Array.from({ length: 15 }, (_, i) => `fn${i}()`)
    const chunk = makeChunk({ body: bodyParts.join('\n') })
    const imports = extractRelevantImports(fileContent, chunk)

    assert.ok(imports.length <= 8)
  })
})

// ── buildScopeContexts ──

describe('buildScopeContexts', () => {
  test('groups methods by enclosing class', () => {
    const tags: RawChunk[] = [
      makeChunk({
        id: 'cls',
        symbolName: 'AuthService',
        symbolKind: 'class',
        signature: 'class AuthService implements IAuth',
        body: 'class AuthService {\n  login() {}\n  logout() {}\n}',
        startLine: 1,
        endLine: 50
      }),
      makeChunk({
        id: 'm1',
        symbolName: 'login',
        symbolKind: 'method',
        signature: 'login(): Promise<void>',
        isPublic: true,
        startLine: 5,
        endLine: 15
      }),
      makeChunk({
        id: 'm2',
        symbolName: 'logout',
        symbolKind: 'method',
        signature: 'logout(): void',
        isPublic: true,
        startLine: 16,
        endLine: 25
      })
    ]
    const contexts = buildScopeContexts(tags)

    assert.ok(contexts.has('AuthService'))
    const ctx = contexts.get('AuthService')!
    assert.equal(ctx.className, 'AuthService')
    assert.equal(ctx.classKind, 'class')
    assert.ok(ctx.siblingMethodSignatures.length >= 1)
  })

  test('returns empty map for files with no classes', () => {
    const tags: RawChunk[] = [makeChunk({ symbolKind: 'function', startLine: 1, endLine: 10 })]
    const contexts = buildScopeContexts(tags)

    assert.equal(contexts.size, 0)
  })
})

// ── buildScopeHeader ──

describe('buildScopeHeader', () => {
  test('includes class signature', () => {
    const scope = {
      className: 'AuthService',
      classKind: 'class' as const,
      classSignature: 'class AuthService implements IAuth',
      classDecorators: ['@Injectable()'],
      parentClassImports: [],
      siblingMethodSignatures: ['login(): Promise<void>', 'logout(): void']
    }
    const header = buildScopeHeader(scope, true)

    assert.ok(header.includes('# Class: class AuthService implements IAuth'))
    assert.ok(header.includes('# Class decorators: @Injectable()'))
    assert.ok(header.includes('login()'))
    assert.ok(header.includes('logout()'))
  })

  test('omits siblings when disabled', () => {
    const scope = {
      className: 'Foo',
      classKind: 'class' as const,
      classSignature: 'class Foo',
      classDecorators: [],
      parentClassImports: [],
      siblingMethodSignatures: ['bar(): void']
    }
    const header = buildScopeHeader(scope, false)

    assert.ok(!header.includes('Other public methods'))
  })
})

// ── Summary ──

// Report handled by test runner
