// Migration test runner entrypoint (used by: npx tsx src/main/services/__tests__/run-tests.ts)
import './generalist-migration.test'
import './execution-pipeline.test'
import './ipc-pipeline-contracts.test'
import './event-sequence.test'
import './agent-services.test'
import './mcp-server-service.test'
import './preprocessing.test'
import './description-cache.test'
import './code-graph-logic.test'
import './vector-search.test'
import './code-graph-db.test'
import './mcp-tool-wiring.test'
