/**
 * Tests for TrackRepository + migration 141 (chat_worktrees → work_tracks).
 *
 * The uniqueness rules are the point of this table, not incidental hygiene:
 * git refuses to check one branch out in two worktrees, so if the DB let two
 * owners claim the same branch we would only find out from a raw git error at
 * spawn time. These tests pin both constraints, the rule that retained work
 * outlives whatever created it, and the reason the owner FK had to go: a
 * blueprint run is not a conversation row.
 *
 * Skips gracefully if better-sqlite3 native module is incompatible.
 */
import assert from 'node:assert/strict'
import { test, describe } from '../../../services/__tests__/test-harness'
import { trySetupTestDb, seedConversation } from './db-test-helper'
import { seedWorkspace } from '../../test-helpers'

const env = trySetupTestDb()

if (!env) {
  describe('TrackRepository (skipped — native module unavailable)', () => {
    test('create() persists a track', () => {}, { skipReason: 'no DB' })
  })
} else {
  const { db, wsId } = env
  const { trackRepository } = require('../track.repository')

  const make = (
    ownerId: string,
    branchName: string,
    path: string,
    workspaceId = wsId,
    ownerKind = 'chat'
  ): ReturnType<typeof trackRepository.create> =>
    trackRepository.create({
      workspaceId,
      ownerKind,
      ownerId,
      branchName,
      path,
      baseBranch: 'main'
    })

  describe('TrackRepository.create', () => {
    test('persists and maps every column', () => {
      const convId = seedConversation(db, wsId, 'Create')
      const t = make(convId, 'feat/create', '/tmp/wt/create')

      assert.equal(t.workspaceId, wsId)
      assert.equal(t.ownerKind, 'chat')
      assert.equal(t.ownerId, convId)
      assert.equal(t.branchName, 'feat/create')
      assert.equal(t.path, '/tmp/wt/create')
      assert.equal(t.baseBranch, 'main')
      assert.equal(t.status, 'active')
      assert.equal(t.landingMode, null, 'null means "inherit the workspace default"')
      assert.equal(t.landedAt, null)
      assert.equal(t.landedInto, null)
      assert.ok(t.id, 'id is generated by the table default')
      assert.ok(t.createdAt, 'created_at is defaulted')
      assert.equal(t.lastUsedAt, null, 'unused until a turn touches it')
    })

    test('rejects a second track for the same owner', () => {
      const convId = seedConversation(db, wsId, 'One tree only')
      make(convId, 'feat/first', '/tmp/wt/first')

      assert.throws(() => make(convId, 'feat/second', '/tmp/wt/second'), /UNIQUE constraint failed/)
    })

    test('a blueprint track and a chat track coexist under the same id', () => {
      // The whole reason owner_kind exists. Under the old schema this row was
      // impossible: owner_id had a foreign key into conversations, and a
      // blueprint run id is not a conversation.
      const sharedId = seedConversation(db, wsId, 'Shared id')
      make(sharedId, 'feat/chat-side', '/tmp/wt/chat-side')
      const bp = make(sharedId, 'feat/blueprint-side', '/tmp/wt/bp-side', wsId, 'blueprint')

      assert.equal(bp.ownerKind, 'blueprint')
      assert.equal(trackRepository.findByOwner('chat', sharedId)?.branchName, 'feat/chat-side')
      assert.equal(
        trackRepository.findByOwner('blueprint', sharedId)?.branchName,
        'feat/blueprint-side'
      )
    })

    test('accepts an owner id that is not a row anywhere', () => {
      // Synthetic ids like `blueprint:<uuid>` and `mpa:<runId>` exist only in
      // memory. A foreign key made every non-chat writer unrepresentable.
      const t = make(
        'blueprint:not-a-row',
        'feat/synthetic',
        '/tmp/wt/synthetic',
        wsId,
        'blueprint'
      )
      assert.equal(t.ownerId, 'blueprint:not-a-row')
    })

    test('rejects two owners claiming the same branch in one workspace', () => {
      const a = seedConversation(db, wsId, 'Holder')
      const b = seedConversation(db, wsId, 'Contender')
      make(a, 'feat/contested', '/tmp/wt/contested-a')

      assert.throws(
        () => make(b, 'feat/contested', '/tmp/wt/contested-b'),
        /UNIQUE constraint failed/,
        'git allows one worktree per branch — the DB must reject this first'
      )
    })

    test('allows the same branch name in a different workspace', () => {
      const otherWs = seedWorkspace(db, 'track-other-ws')
      const a = seedConversation(db, wsId, 'Ours')
      const b = seedConversation(db, otherWs, 'Theirs')

      make(a, 'feat/shared-name', '/tmp/wt/ours')
      const other = make(b, 'feat/shared-name', '/tmp/wt/theirs', otherWs)

      assert.equal(other.workspaceId, otherWs, 'uniqueness is per workspace, not global')
    })

    test('rejects two tracks at the same path', () => {
      const a = seedConversation(db, wsId, 'Path A')
      const b = seedConversation(db, wsId, 'Path B')
      make(a, 'feat/path-a', '/tmp/wt/same-path')

      assert.throws(
        () => make(b, 'feat/path-b', '/tmp/wt/same-path'),
        /UNIQUE constraint failed: work_tracks.path/
      )
    })
  })

  describe('TrackRepository lookups', () => {
    test('findByOwner returns the row, or undefined when absent', () => {
      const convId = seedConversation(db, wsId, 'Lookup')
      assert.equal(trackRepository.findByOwner('chat', convId), undefined)

      make(convId, 'feat/lookup', '/tmp/wt/lookup')
      assert.equal(trackRepository.findByOwner('chat', convId)?.branchName, 'feat/lookup')
    })

    test('findByBranch is scoped to the workspace', () => {
      const convId = seedConversation(db, wsId, 'By branch')
      make(convId, 'feat/by-branch', '/tmp/wt/by-branch')

      assert.equal(trackRepository.findByBranch(wsId, 'feat/by-branch')?.ownerId, convId)
      assert.equal(
        trackRepository.findByBranch('track-other-ws', 'feat/by-branch'),
        undefined,
        'another workspace must not see this branch as taken'
      )
    })

    test('findByWorkspace excludes other workspaces', () => {
      const isolatedWs = seedWorkspace(db, 'track-isolated-ws')
      const convId = seedConversation(db, isolatedWs, 'Isolated')
      make(convId, 'feat/isolated', '/tmp/wt/isolated', isolatedWs)

      const rows = trackRepository.findByWorkspace(isolatedWs)
      assert.equal(rows.length, 1)
      assert.equal(rows[0].ownerId, convId)
    })

    test('findAll spans workspaces — the reaper needs every row', () => {
      const before = trackRepository.findAll().length
      const reaperWs = seedWorkspace(db, 'track-reaper-ws')
      const convId = seedConversation(db, reaperWs, 'Reaper')
      make(convId, 'feat/reaper', '/tmp/wt/reaper', reaperWs)

      assert.equal(trackRepository.findAll().length, before + 1)
    })
  })

  describe('TrackRepository mutations', () => {
    test('markRemoving flips status without deleting the tombstone', () => {
      const convId = seedConversation(db, wsId, 'Removing')
      const t = make(convId, 'feat/removing', '/tmp/wt/removing')

      trackRepository.markRemoving(t.id)

      const after = trackRepository.findByOwner('chat', convId)
      assert.equal(after?.status, 'removing')
      assert.ok(after, 'row survives so a crash mid-teardown is recoverable')
    })

    test('touch records last_used_at', () => {
      const convId = seedConversation(db, wsId, 'Touch')
      const t = make(convId, 'feat/touch', '/tmp/wt/touch')
      assert.equal(t.lastUsedAt, null)

      trackRepository.touch(t.id)

      assert.ok(trackRepository.findByOwner('chat', convId)?.lastUsedAt)
    })

    test('deleteByOwner removes the row and frees the branch', () => {
      const convId = seedConversation(db, wsId, 'Delete')
      make(convId, 'feat/freed', '/tmp/wt/freed')

      assert.equal(trackRepository.deleteByOwner('chat', convId), 1)
      assert.equal(trackRepository.findByOwner('chat', convId), undefined)

      // The branch must be claimable again once released.
      const next = seedConversation(db, wsId, 'Successor')
      assert.ok(make(next, 'feat/freed', '/tmp/wt/freed-2'))
    })

    test('markRetained parks the track and detaches it from its owner', () => {
      const convId = seedConversation(db, wsId, 'Retained')
      const t = make(convId, 'feat/retained', '/tmp/wt/retained')

      trackRepository.markRetained(t.id)

      const after = trackRepository.findById(t.id)
      assert.equal(after?.status, 'retained')
      assert.equal(
        after?.ownerId,
        null,
        'parked work belongs to the user, not to a chat that is about to be deleted'
      )
      assert.equal(
        trackRepository.findByOwner('chat', convId),
        undefined,
        'and it must never be routed a turn again'
      )
    })

    test('deleting the owner row cannot destroy the track', () => {
      const convId = seedConversation(db, wsId, 'Detach')
      const t = make(convId, 'feat/detach', '/tmp/wt/detach')

      db.prepare('DELETE FROM conversations WHERE id = ?').run(convId)

      // v139 used ON DELETE CASCADE, which made "retain dirty trees" a lie:
      // chat delete removed the only record of the directory microseconds after
      // release() decided to keep it, leaving a checkout nothing could find.
      // v140 patched that with SET NULL; v141 removed the foreign key entirely,
      // so nothing outside this table can reach in and change it at all.
      const after = trackRepository.findById(t.id)
      assert.ok(after, 'the record of the work on disk survives its owner')
      assert.equal(after?.ownerId, convId, 'no FK means no cascade and no silent NULLing')
    })

    test('several retained tracks can coexist — UNIQUE tolerates NULLs', () => {
      const first = seedConversation(db, wsId, 'Detached A')
      const second = seedConversation(db, wsId, 'Detached B')
      const a = make(first, 'feat/detached-a', '/tmp/wt/detached-a')
      const b = make(second, 'feat/detached-b', '/tmp/wt/detached-b')

      trackRepository.markRetained(a.id)
      trackRepository.markRetained(b.id)

      const parked = trackRepository
        .findByWorkspace(wsId)
        .filter(
          (w: { ownerId: string | null; branchName: string }) =>
            w.ownerId === null && w.branchName.startsWith('feat/detached-')
        )
      assert.equal(parked.length, 2, 'a UNIQUE owner must not cap parked work at one')
    })
  })
}
